// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["./BaseVersionManager","./utils"],function(k,l){function h(){this.versions=[{version:"1.0",description:"The version embedded in portal 10.3 final.",upgrader:function(a){return a},compatible:!0},{version:"1.1",description:"The version embedded in online3.6, and used in developer edition 1.0.",upgrader:function(a){a.widgetOnScreen&&a.widgetOnScreen.panel&&("themes/FoldableTheme/panels/TitlePanel/Panel"===a.widgetOnScreen.panel.uri||"jimu/BaseWidgetPanel"===a.widgetOnScreen.panel.uri)&&(a.widgetOnScreen.panel.uri=
"jimu/PreloadWidgetIconPanel");return a},compatible:!0},{version:"1.2",description:"The version embedded in online3.7.",upgrader:function(a){var b=0;if(a.widgetOnScreen&&a.widgetOnScreen.widgets){for(var c=!1,b=0;b<a.widgetOnScreen.widgets.length;b++)"widgets/Splash/Widget"===a.widgetOnScreen.widgets[b].uri&&(c=!0);c||a.widgetOnScreen.widgets.push({uri:"widgets/Splash/Widget",visible:!1,positionRelativeTo:"browser",version:"1.2"});c=!1;for(b=0;b<a.widgetOnScreen.widgets.length;b++)"widgets/TimeSlider/Widget"===
a.widgetOnScreen.widgets[b].uri&&(c=!0);c||a.widgetOnScreen.widgets.push({uri:"widgets/TimeSlider/Widget",visible:!1,position:{bottom:55,left:7},version:"1.2"});c=!1;for(b=0;b<a.widgetOnScreen.widgets.length;b++)"widgets/Swipe/Widget"===a.widgetOnScreen.widgets[b].uri&&(c=!0);c||a.widgetOnScreen.widgets.push({uri:"widgets/Swipe/Widget",visible:!1,position:{top:145,left:7},version:"1.2"})}return a},compatible:!0},{version:"1.3",description:"The version embedded in online3.8 \x26 online3.9.",upgrader:function(a){(function(b){l.visitElement(b,
function(b){b.positionRelativeTo&&(b.position?b.position.relativeTo=b.positionRelativeTo:b.position={relativeTo:b.positionRelativeTo},b.panel&&(b.panel.position?b.panel.position.relativeTo=b.panel.positionRelativeTo:b.panel.position={relativeTo:b.panel.positionRelativeTo}))});var c=b.widgetOnScreen;c&&c.panel&&c.panel.positionRelativeTo&&(c.panel.position?c.panel.position.relativeTo=c.panel.positionRelativeTo:c.panel.position={relativeTo:c.panel.positionRelativeTo});(c=b.widgetPool)&&c.panel&&c.panel.positionRelativeTo&&
(c.panel.position?c.panel.position.relativeTo=c.panel.positionRelativeTo:c.panel.position={relativeTo:c.panel.positionRelativeTo})})(a);a.widgetOnScreen&&a.widgetOnScreen.panel&&"jimu/PreloadWidgetIconPanel"===a.widgetOnScreen.panel.uri&&(a.widgetOnScreen.panel.uri="jimu/OnScreenWidgetPanel");(function(b){if(b.widgetOnScreen&&b.widgetOnScreen.widgets&&b.theme&&"FoldableTheme"===b.theme.name){var c=null,a=null;if(c=b.widgetOnScreen.widgets[4])void 0!==c.position.top?(c={position:{left:205,top:45}},
a={position:{left:255,top:45}}):(c={position:{left:205,bottom:55}},a={position:{left:255,bottom:55}}),b.widgetOnScreen.widgets.splice(7,0,c,a)}})(a);(function(){for(var b=0,c=0,d=!1,b=0;b<a.widgetOnScreen.widgets.length;b++)if("widgets/Geocoder/Widget"===a.widgetOnScreen.widgets[b].uri){d=!0;break}for(var e=!1,c=0;c<a.widgetOnScreen.widgets.length;c++)if("widgets/Search/Widget"===a.widgetOnScreen.widgets[c].uri){e=!0;break}!e&&d&&(b=a.widgetOnScreen.widgets[b],b.uri="widgets/Search/Widget",b.name=
"Search")})(a);(function(b){for(var a=0,a=b.widgetOnScreen.widgets.length-1;0<=a;a--){var d=b.widgetOnScreen.widgets[a];if("widgets/Swipe/Widget"===d.uri&&!d.closeable&&(b.widgetOnScreen.widgets.splice(a,1),!1!==d.visible)){d.closeable=!0;var e;a:{for(e=e=0;e<b.widgetOnScreen.widgets.length;e++)if(!b.widgetOnScreen.widgets[e].uri)break a;e=-1}0<=e&&(d.position=b.widgetOnScreen.widgets[e].position,b.widgetOnScreen.widgets[e]=d)}"widgets/TimeSlider/Widget"===d.uri&&(!1===d.visible?b.widgetOnScreen.widgets.splice(a,
1):d.closeable=!0)}})(a);a.widgetOnScreen.widgets.push({uri:"widgets/ZoomSlider/Widget",position:{top:5,left:7},version:"1.3"});a.loadingPage||(a.loadingPage={backgroundColor:"#508dca",backgroundImage:{visible:!1},loadingGif:{visible:!0,uri:"configs/loading/images/predefined_loading_1.gif",width:58,height:58}});return a},compatible:!0},{version:"1.4",description:"The version embedded in online3.10.",upgrader:function(a){if(a.theme){var b=a.theme.name;if(("FoldableTheme"===b||"JewelryBoxTheme"===b)&&
a.widgetOnScreen){var c=a.widgetOnScreen.widgets;if(c&&0<c.length)for(var b="themes/"+b+"/widgets/HeaderController/Widget",d=null,e=0;e<c.length;e++)(d=c[e])&&d.uri===b&&d.position&&310===d.position.paddingRight&&(d.position.paddingRight=275)}}return a},compatible:!0},{version:"2.0beta",description:"The version for Developer Edition beta 2.0.",upgrader:function(a){a.keepAppState=!0;return a},compatible:!0},{version:"2.0",description:"The version for Online 4.1.",upgrader:function(a){return a},compatible:!0},
{version:"2.0.1",description:"The version for Developer Edition 2.0.",upgrader:function(a){return a},compatible:!0},{version:"2.1",description:"The version for Online 4.2.",upgrader:function(a){return a},compatible:!0},{version:"2.2",description:"The version for Online 4.3.",upgrader:function(a){return a},compatible:!0},{version:"2.3",description:"The version for Online 4.4.",upgrader:function(a){function b(a,c){if(!a||!c)return!1;for(var e in c)if(c.hasOwnProperty(e))if("object"===typeof c[e]){if(!b(a[e],
c[e]))return!1}else if(a[e]!==c[e])return!1;return!0}function c(a){function c(){var c=b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),e=b(a[12],{position:{top:10,right:195}});return c&&e}function e(){var c=b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,bottom:45}}),e=b(a[12],{position:{left:15,top:233}});return c&&e}function d(){var c=b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),e=b(a[12],{position:{right:15,top:195}});return c&&e}(function(){var c=
b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),e=b(a[12],{position:{left:240,top:53}});return c&&e})()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,top:159},version:"2.3"}):c()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,top:159},version:"2.3"}):e()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,bottom:195},version:"2.3"}):d()&&a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,
top:159},version:"2.3"})}function d(a){function c(){var c=b(a[9],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}),e=b(a[2],{uri:"widgets/Search/Widget",position:{left:55,top:5}}),d=b(a[4],{position:{left:7,bottom:70}});return c&&e&&d}function e(){var c=b(a[9],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}),e=b(a[2],{uri:"widgets/Search/Widget",position:{right:2,top:2,relativeTo:"browser"}}),d=b(a[4],{position:{left:7,bottom:70}});return c&&e&&d}(function(){var c=b(a[9],{uri:"widgets/MyLocation/Widget",
position:{left:7,top:110}}),e=b(a[2],{uri:"widgets/Search/Widget",position:{left:55,top:5}}),d=b(a[4],{position:{left:55,top:45}});return c&&e&&d}()||c()||e())&&a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:148,left:7},version:"2.3"})}(function(a,f,g){a=a.theme&&a.theme.name;if("FoldableTheme"===a)if(b(f[11],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}))f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:150,left:7},version:"2.3"});else if(b(f[11],
{uri:"widgets/MyLocation/Widget",position:{left:12,bottom:164}}))f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:12,bottom:203},version:"2.3"}),g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{right:12,top:211},version:"2.3"});else{if(b(f[11],{uri:"widgets/MyLocation/Widget",position:{left:164,bottom:14}})){f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:203,bottom:14,height:30},version:"2.3"});for(a=0;a<f.length;a++){var e=f[a];b(e,{uri:"widgets/Scalebar/Widget",
position:{left:220,bottom:5}})&&(e.position.left=288);b(e,{uri:"widgets/Coordinate/Widget",position:{left:395,bottom:5}})&&(e.position.left=463)}g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:209,left:12},version:"2.3"})}}else if("BillboardTheme"===a)c(f);else if("BoxTheme"===a)f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:10,top:131},version:"2.3"});else if("JewelryBoxTheme"===a)d(f);else if("LaunchpadTheme"===a){if(b(f[6],{uri:"widgets/MyLocation/Widget",
position:{left:25,top:215}})||b(f[6],{uri:"widgets/MyLocation/Widget",position:{left:25,top:215}}))f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:255,left:25},version:"2.3"}),g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{right:10,bottom:238},version:"2.3"})}else"PlateauTheme"===a?(b(f[6],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}})&&f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:149,left:7},version:2.3}),b(f[6],{uri:"widgets/MyLocation/Widget",
position:{left:12,bottom:164}})&&f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:12,bottom:201},version:2.3})):"TabTheme"===a&&b(f[11],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}})&&f.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:149,left:7},version:"2.3"})})(a,a.widgetOnScreen.widgets,a.mobileLayout&&a.mobileLayout.widgetOnScreen&&a.mobileLayout.widgetOnScreen.widgets);return a},compatible:!0},{version:"2.4",description:"The version for Online 5.1.",
upgrader:function(a){return a},compatible:!0},{version:"2.5",description:"The version for Online 5.2.",upgrader:function(a){function b(a,d){if(!a||!d)return!1;for(var c in d)if(d.hasOwnProperty(c))if("object"===typeof d[c]){if(!b(a[c],d[c]))return!1}else if(a[c]!==d[c])return!1;return!0}(function(a,d){a=a.theme&&a.theme.name;if("BillboardTheme"===a){a=b(d[8],{position:{left:60,top:53}});var c=b(d[8],{position:{left:15,top:53}});a||c?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,
top:8},version:"2.5"}):d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,bottom:55},version:"2.5"})}else if("BoxTheme"===a){a:{a=0;for(c=d.length;a<c;a++){var f=d[a];if(f&&f.uri&&"themes/BoxTheme/widgets/BoxController/Widget"===f.uri){a=f;break a}}a=null}b(a,{position:{right:0,bottom:0}})?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,bottom:8},version:"2.5"})}else"DartTheme"===
a?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"FoldableTheme"===a?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"DashboardTheme"===a?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"JewelryBoxTheme"===a?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"LaunchpadTheme"===a?d.push({uri:"widgets/FullScreen/Widget",visible:!1,
position:{right:70,top:20},version:"2.5"}):"PlateauTheme"===a?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):"TabTheme"===a&&(b(d[7],{position:{left:45,top:45}})?d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,top:8},version:"2.5"}):d.push({uri:"widgets/FullScreen/Widget",visible:!1,position:{right:8,bottom:55},version:"2.5"}))})(a,a.widgetOnScreen.widgets);return a},compatible:!0},{version:"2.6",description:"The version for Online 5.3.",
upgrader:function(a){return a},compatible:!0},{version:"2.7",description:"The version for Online 5.4.",upgrader:function(a){return a},compatible:!0},{version:"2.8",description:"The version for Online 6.1.",upgrader:function(a){function b(a){var b=[];if("object"===typeof a)for(var c in a){var f=a[c];"FeatureStatistics"===f.type&&b.push(f)}return b}(function(a){(a=a.dataSource&&a.dataSource.dataSources)&&(a=b(a))&&a.length&&a.forEach(function(a){(a=a.dataSchema&&a.dataSchema.statistics)&&a.length&&
a.forEach(function(a){if(a&&"count"===a.statisticType&&"count"===a.outStatisticFieldName)a.outStatisticFieldName="STAT_COUNT";else{var b;b=(b=a.outStatisticFieldName)&&b.toUpperCase();a.outStatisticFieldName=b}})})})(a);return a},compatible:!0},{version:"2.9",description:"The version for Online 6.2.",upgrader:function(a){return a},compatible:!0},{version:"2.10",description:"The version for Online 6.3.",upgrader:function(a){return a},compatible:!0}];this.isCompatible=function(a,b){a=this.getVersionIndex(a);
b=this.getVersionIndex(b);for(a+=1;a<=b;a++)if(!1===this.versions[a].compatible)return!1;return!0}}h.prototype=new k;return h.prototype.constructor=h});