// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/string ./convert ./QuerySourceSetting ./settingComponents ./SettingBoxedDivs ./SettingBufferBlock ./SettingCheckboxLabeled ./SettingContainer ./SettingDropdownLabeled ./SettingFieldListLabeled ./SettingInputLabeled ./SettingObject ./SettingOptionsTable ./SettingStaticText".split(" "),function(g,v,f,p,q,l,m,r,w,n,x,t,h,k,y,z,e,A,B,u){return v(A,{_inputControl:null,_mainControl:null,_detailsDiv:null,
_detailsTitle:null,_detailsCheckbox:null,_sourceDisplay:null,_iCurrentSource:-1,_sourceMenuItems:[],_newSourceTypeMenuItems:[],_nls:null,_webmapFeatureLayers:[],_fieldListPicker:null,_displayFieldInput:null,constructor:function(b,a,c,d,C,g){this._nls=a;this._map=d;this._webmapFeatureLayers=C;this._portalUrl=g;this._newSourceTypeMenuItems=[a.groupingLabels.featureLayerDetails,a.groupingLabels.geocoderDetails];this._inputControl=new B(null,"third-width","",a.propertyLabels.name,null,"",f.hitch(this,
this._onRowSelected),f.hitch(this,this._onRowDeleted),f.hitch(this,this._onRowMoved));this._detailsDiv=n.container("two-thirds-width optionsTableHeaderHeight","majorTrailingVertGap",[]);b=n.addTextButtonDropdownCtl("",a.buttons.addSearchSource,this._newSourceTypeMenuItems);this.own(l(b.ctl,"click",f.hitch(this,this._onAddSearchSourceMenuItemClick)));this._mainControl=new k(null,c||"","majorTrailingVertGap",a.groupingLabels.searchSources,"full-width",[new e("allPlaceholder",!1,"full-width","third-width",
"two-thirds-width",a.propertyLabels.placeholderTextForAllSources),new h("showInfoWindowOnSelect","full-width","third-width","two-thirds-width",a.propertyLabels.showPopupForFoundItem),new x(null,[b.div,n.container("full-width flexbox","majorTrailingHorizGap",[this._inputControl.div(),this._detailsDiv])])]);this._mainDiv=this._mainControl.div()},setConfig:function(){this._mainControl.setConfig(this._config);this._sourceMenuItems=g.map(this._config.sources,function(b){return{item:b.name}});this._inputControl.setValue(this._sourceMenuItems);
0<this._sourceMenuItems.length&&this._inputControl.selectTableRow(0)},getConfig:function(b,a){this._mainControl.getConfig(this._config);this._setDetails(-1);g.forEach(this._config.sources,function(b){"locator"===b.type?b.url||a.push(m.substitute(this._nls.problems.noSearchSourceURL,{sourceName:b.name})):0===b.searchFields.length&&a.push(m.substitute(this._nls.problems.noSearchSourceFields,{sourceName:b.name}));0>b.buffer.bufferUnitsMenu[0].indexOf("1")&&a.push(m.substitute(this._nls.problems.noBufferUnitsForSearchSource,
{sourceName:b.name}))},this)},_onAddSearchSourceMenuItemClick:function(b){var a,c={};if(b.target.innerText===this._newSourceTypeMenuItems[0]){var d=new w({nls:this._nls.querySourceSetting,map:this._map,appConfig:{portalUrl:this._portalUrl}});a=f.clone(this._config.searchSourceTemplates.query);d.setConfig({name:a.name||"",placeholder:a.placeholder||"",searchFields:a.searchFields||[],displayField:a.displayField||"",maxSuggestions:a.maxSuggestions||6,maxResults:a.maxResults||6,zoomScale:a.zoomScale||
5E4,exactMatch:a.exactMatch,searchInCurrentMapExtent:a.searchInCurrentMapExtent,type:a.type||"query",layerId:a.layerId,url:a.url||""});d._openQuerySourceChooser();d.own(l(d,"select-query-source-ok",f.hitch(this,function(b){a.name=b.name;a.layerId=b.layerInfo?b.layerInfo.id:null;a.url=b.url;a.buffer=f.clone(this._config.bufferTemplate);a.fieldMenuItems=[];(b=b.definition&&b.definition.fields)&&g.map(b,function(b){a.fieldMenuItems.push({label:b.alias||b.name,value:b.name})});this._config.sources.push(a);
c.item=a.name;this._sourceMenuItems.push(c);this._inputControl.addRowToTable(c);this._inputControl.selectTableRow(this._config.sources.length-1);d.destroy();d=null})));d.own(l(d,"select-query-source-cancel",function(){d.destroy();d=null}))}else a=f.clone(this._config.searchSourceTemplates.locator),a.singleLineFieldName=null,a.buffer=f.clone(this._config.bufferTemplate),this._config.sources.push(a),c.item=a.name,this._sourceMenuItems.push(c),this._inputControl.addRowToTable(c),this._inputControl.selectTableRow(this._config.sources.length-
1)},_setDetails:function(b){var a=this._sourceMenuItems.length;this._removeCurrentDetails();0<=b&&b<a&&(a=this._config.sources[b],"query"===a.type?(this._fieldListPicker=new z("searchFields",this._nls,"full-width","details-label","details-value",this._nls.propertyLabels.searchFields,this._nls.hints.csvNameList,a.fieldMenuItems),this._displayFieldInput=new y("displayField","full-width","details-label","details-value",this._nls.propertyLabels.displayField,"",a.fieldMenuItems,f.hitch(this,this._onChangeField)),
this._sourceDisplay=new k(null,"","majorTrailingVertGap",this._nls.groupingLabels.featureLayerDetails,"full-width",[new k(null,"full-width","minorTrailingHorizGap",[new u(null,"details-label inline-block",this._nls.querySourceSetting.layerSource),new u(null,"details-value inline-block wrapText",a.url)]),new e("name",!1,"full-width","details-label","details-value",this._nls.propertyLabels.name,a.name),new e("placeholder",!1,"full-width","details-label","details-value",this._nls.propertyLabels.placeholderText),
this._fieldListPicker,this._displayFieldInput,new e("maxSuggestions",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumSuggestions,"6",null,null,null,{min:1,max:10,places:0}),new e("maxResults",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumResults,"6",null,null,null,{min:1,max:10,places:0}),new e("zoomScale",!0,"full-width","details-label","details-value",this._nls.propertyLabels.zoomScale,"50000","","1:",null,{min:0,places:0}),new h("exactMatch",
"full-width","details-label","details-value",this._nls.propertyLabels.exactMatch),new h("searchInCurrentMapExtent","full-width","details-label","details-value",this._nls.propertyLabels.limitSearchToMapExtent),new t("buffer",this._nls,"full-width","details-label","details-value",this._config.bufferTemplate,this._nls.propertyLabels.bufferDefaultDistance,"100")])):"locator"===a.type&&(this._sourceDisplay=new k(null,"","majorTrailingVertGap",this._nls.groupingLabels.geocoderDetails,"full-width",[new e("url",
!1,"full-width","details-label","details-value",this._nls.propertyLabels.url),new e("name",!1,"full-width","details-label","details-value",this._nls.propertyLabels.name),new e("placeholder",!1,"full-width","details-label","details-value",this._nls.propertyLabels.placeholderText),new e("countryCode",!1,"full-width","details-label","details-value",this._nls.propertyLabels.countryRegionCodes,this._nls.placeholders.countryRegionCodes),new e("maxSuggestions",!0,"full-width","details-label","details-value",
this._nls.propertyLabels.maximumSuggestions,"6",null,null,null,{min:1,max:10,places:0}),new e("maxResults",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumResults,"6",null,null,null,{min:1,max:10,places:0}),new e("zoomScale",!0,"full-width","details-label","details-value",this._nls.propertyLabels.zoomScale,"50000","","1:",null,{min:0,places:0}),new h("searchInCurrentMapExtent","full-width","details-label","details-value",this._nls.propertyLabels.limitSearchToMapExtent),
new t("buffer",this._nls,"full-width","details-label","details-value",this._config.bufferTemplate,this._nls.propertyLabels.bufferDefaultDistance,"100")])),this._sourceDisplay&&(a.buffer.bufferUnitsMenu=r.unitCodesToLabels(jimuNls.units,a.buffer.bufferUnitsMenu),this._sourceDisplay.setConfig(a),q.place(this._sourceDisplay.div(),this._detailsDiv),p.remove(this._detailsDiv,"hidden"),this._iCurrentSource=b))},_convertLayerIdToLayerName:function(b){var a=b;g.some(this._webmapFeatureLayers,function(c){return c.layerId===
b?(a=c.name,!0):!1});return a},_convertLayerNameToLayerId:function(b){var a=b;g.some(this._webmapFeatureLayers,function(c){return c.name===b?(a=c.layerId,!0):!1});return a},_onChangeFeatureLayer:function(b){var a,c=[];0<=this._iCurrentSource&&(a=this._config.sources[this._iCurrentSource],g.some(this._webmapFeatureLayers,f.hitch(this,function(d){return b===d.layerId?(a.name=d.layerId,a.searchFields=[],a.displayField=d.displayField,a.layerId=d.layerId,a.url=d.url,g.map(d.fields,function(a){c.push({label:a.alias||
a.name,value:a.name})}),this._fieldListPicker.setFieldList(c),this._fieldListPicker.setDisplay(),this._displayFieldInput.setOptions(c),this._inputControl.renameTableRow(this._iCurrentSource,d.name),!0):!1})))},_onChangeField:function(b){var a;0<=this._iCurrentSource&&(a=this._config.sources[this._iCurrentSource],a.displayField=b)},_onRowSelected:function(b){this._setDetails(b.rowIndex)},_onRowMoved:function(b,a){var c;this._removeCurrentDetails();c=a?b.rowIndex+1:b.rowIndex-1;a=this._sourceMenuItems.splice(c,
1);c=this._config.sources.splice(c,1);this._sourceMenuItems.splice(b.rowIndex,0,a[0]);this._config.sources.splice(b.rowIndex,0,c[0]);this._inputControl.selectTableRow(b.rowIndex)},_onRowDeleted:function(b,a,c){this._removeCurrentDetails();this._sourceMenuItems.splice(c,1);this._config.sources.splice(c,1);0<this._sourceMenuItems.length&&this._inputControl.selectTableRow(0)},_removeCurrentDetails:function(){var b;0<=this._iCurrentSource&&(p.add(this._detailsDiv,"hidden"),b=this._config.sources[this._iCurrentSource],
this._sourceDisplay.getConfig(b),b.buffer.bufferUnitsMenu=r.labelsToUnitCodes(jimuNls.units,b.buffer.bufferUnitsMenu),"query"===b.type&&(b.name=this._convertLayerIdToLayerName(b.name)),q.empty(this._detailsDiv),this._sourceDisplay=null,this._iCurrentSource=-1)}})});