// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/_filter/EditTable.html":'\x3cdiv\x3e\r\n    \x3cdiv class\x3d"jimu-multiple-set-container"\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"" class\x3d"items-list-content items-list-header"  \x3e\r\n        \x3cdiv class\x3d"item"\x3e\r\n          \x3cdiv class\x3d"label jimu-ellipsis" title\x3d"${Nls.value}"\x3e${Nls.value}\x3c/div\x3e\r\n          \x3cdiv class\x3d"label jimu-ellipsis" title\x3d"${CommonNls.label}"\x3e${CommonNls.label}\x3c/div\x3e\r\n          \x3cdiv class\x3d"label checkboxHeader jimu-ellipsis" title\x3d"${CommonNls.defaults}"\x3e${CommonNls.defaults}\x3c/div\x3e\r\n          \x3cdiv class\x3d"label lableR jimu-ellipsis" title\x3d"${CommonNls.actions}"\x3e${CommonNls.actions}\x3c/div\x3e\r\n        \x3c/div\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"listContent" class\x3d"items-list-content" data-dojo-attach-event\x3d"click:_onListContentClicked, dblclick:_onListContentDblClicked"\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e'}});
define("dojo/_base/lang dojo/_base/html dojo/Evented dojo/on dojo/dom-attr dojo/_base/declare dijit/_WidgetBase dojo/query dijit/form/ValidationTextBox dijit/form/NumberTextBox dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./EditTable.html jimu/utils".split(" "),function(k,c,n,m,l,p,q,g,r,t,u,v,w,h){return p([q,u,v,n],{templateString:w,currentItem:null,dataList:[],codedValues:null,isNumberField:!0,tableType:"unique",postMixInProperties:function(){this.inherited(arguments);this.CommonNls=
window.jimuNls.common;this.Nls=window.jimuNls.filterBuilder},postCreate:function(){this.inherited(arguments);c.addClass(this.domNode,"jimu-filter-mutcheck-list-value-provider");this.inputType="unique"===this.tableType?"radio":"checkbox"},_onListContentDblClicked:function(a){this.isSearch=!1;var b=a.target||a.srcElement,e=h.getAncestorDom(b,function(a){return c.hasClass(a,"item")},3);if(e&&(c.hasClass(b,"name")||c.hasClass(b,"alias"))&&(!c.hasClass(e,"empty")||!c.hasClass(b,"name"))){this._dijit?(this.editState=
"active",this.updateInputDivPre=this.updateInputDiv,this._dijitPre=this._dijit):this.editState="negative";a=this._getNodeText(b);var d=decodeURIComponent(c.getAttr(b,"data")),e=c.hasClass(e,"custom");this.placeHolder=c.hasClass(b,"name")&&!this.codedValues?d:a;e?c.hasClass(b,"alias")&&this.placeHolder!==this.customLabel?this.currentLabel=a:this.currentLabel=NaN:this.currentLabel=this.isNumberField&&c.hasClass(b,"name")&&!this.codedValues?parseFloat(this.placeHolder):this.placeHolder;l.set(b,"innerHTML",
"");a="";c.hasClass(b,"name")&&(a='\x3cdiv class\x3d"searchBtn"\x3e\x3cdiv class\x3d"jimu-icon jimu-icon-down-arrow-8"\x3e\x3c/div\x3e\x3c/div\x3e');this.updateInputDiv=c.create("div",{"class":"updateInputDiv",innerHTML:'\x3cdiv class\x3d"inputDiv"\x3e\x3c/div\x3e'+a},b);a=g(".inputDiv",this.updateInputDiv)[0];this.searchBtn=g(".searchBtn",this.updateInputDiv)[0];this.own(m(this.updateInputDiv,"dblclick",k.hitch(this,function(a){a.stopPropagation();a.preventDefault()})));d={required:!1,intermediateChanges:!1,
value:this.currentLabel};this.codedValues&&c.hasClass(b,"name")&&(d.disabled=!0);this.isNumberField&&c.hasClass(b,"name")?(d.constraints={pattern:"#####0.##########"},this._dijit=new t(d)):(d.trim=!0,this._dijit=new r(d));this._dijit.startup();this._dijit.on("keydown",function(a){13===(a.keyCode||a.which)&&this._dijit.emit("blur")}.bind(this));this._dijit.on("blur",k.hitch(this,function(){if(this._dijit){var a="Error"!==this._dijit.state?this._dijit.displayedValue:this.currentLabel;this.isNumberField&&
c.hasClass(b,"name")&&"Error"===this._dijit.state&&this._dijit.setValue(parseFloat(a));var a=h.sanitizeHTML(a),e=this._dijit.get("value");""!==e&&e?c.hasClass(b,"name")&&(this.placeHolder===this.customValue||"NaN"===this.placeHolder&&""!==this._dijit.displayedValue)&&(e=h.getAncestorDom(this._dijit.domNode,function(a){return c.hasClass(a,"item")},4),c.removeClass(e,"custom"),this.emit("editTable_itemChanged")):a=this.placeHolder;this.newLabel=a;setTimeout(k.hitch(this,function(){var a;if(this.isSearch||
"active"===this.editState)"active"===this.editState&&(this.currentValLabel=""===this._dijitPre.displayedValue?this.customValue:this.isNumberField?this._getLocalNumber(this._dijitPre.value):this._dijitPre.value,b=this.updateInputDivPre.parentNode,!c.hasClass(b,"name")||"NaN"===this.newLabel||this.newLabel===this.customValue||this._getNodeText(b.nextSibling)!==this.customLabel&&this._dijit.value!==this.customLabel||(c.isDescendant(this.updateInputDiv,b.nextSibling)?this._dijit.set("value",this.currentValLabel):
(a=this.isNumberField?this.currentValLabel:this.newLabel,c.setAttr(b.nextSibling,"data",encodeURIComponent(a)),this._setNodeText(b.nextSibling,a))),a=c.hasClass(b,"name")?""===this._dijitPre.displayedValue?this.customValue:this._dijitPre.value:this.newLabel,c.setAttr(b,"data",a),a=c.hasClass(b,"name")?this.currentValLabel:this.newLabel,this._setNodeText(b,a),this._dijitPre=this.updateInputDivPre=null,this.editState="negative");else{this.currentValLabel=""===this._dijit.displayedValue?this.customValue:
this.isNumberField?this._getLocalNumber(this._dijit.value):this._dijit.value;var b=this.updateInputDiv.parentNode;c.hasClass(b,"name")&&"NaN"!==this.newLabel&&this.newLabel!==this.customValue&&this._getNodeText(b.nextSibling)===this.customLabel&&(a=this.isNumberField?this.currentValLabel:this.newLabel,c.setAttr(b.nextSibling,"data",encodeURIComponent(a)),this._setNodeText(b.nextSibling,a));a=c.hasClass(b,"name")?""===this._dijit.displayedValue?this.customValue:this._dijit.value:this.newLabel;c.setAttr(b,
"data",encodeURIComponent(a));a=c.hasClass(b,"name")?this.currentValLabel:this.newLabel;this._setNodeText(b,a);this._dijit=null;this.isSearch=!1}}),300);this.placeHolder=""}}));c.setStyle(this._dijit.domNode,"width","100%");this._dijit.placeAt(a);g("input",this._dijit.domNode)[1].focus();this.searchBtn&&(this.own(m(this.searchBtn,"click",k.hitch(this,function(a){this.isSearch||(this.isSearch=!0,this.searchTarget=a.target||a.srcElement,this.emit("editTable_openListSelectByName",this.newLabel),a.stopPropagation(),
a.preventDefault())}))),this.codedValues&&this.searchBtn.click())}},_getLocalNumber:function(a){"string"===typeof a&&(a=parseFloat(a));this.emit("editTable_getValLabelsArrayForNumber",!0,[a]);return this.currentValLabel},_setNewLabel:function(a,b){void 0===a&&void 0===b&&(""!==this._dijit.displayedValue?this.codedValues?(b=this._dijit.displayedValue,a=this._getCodeFromCodevalueLabel(b)):(b=a=this._dijit.value,this.isNumberField&&this.newLabel!==this.customValue&&(b=this._getLocalNumber(a))):a=b=this.customValue);
if(this.updateInputDiv&&this.updateInputDiv.parentNode){var e=this.updateInputDiv.parentNode;b!==this.customValue&&this._getNodeText(e.nextSibling)===this.customLabel&&(c.setAttr(e.nextSibling,"data",encodeURIComponent(b)),this._setNodeText(e.nextSibling,b));this.codedValues||(a=a?a:decodeURIComponent(c.getAttr(e,"data")));c.setAttr(e,"data",encodeURIComponent(a));a=e.parentNode;b!==this.customValue&&c.removeClass(a,"custom");this._setNodeText(e,b)}this._dijit=this.updateInputDiv=null},_onListContentClicked:function(a){a=
a.target||a.srcElement;var b=h.getAncestorDom(a,function(a){return c.hasClass(a,"item")},3);b&&(c.hasClass(a,"checkboxEmpty")?c.hasClass(a,"checked")?c.removeClass(a,"checked"):c.addClass(a,"checked"):c.hasClass(a,this.inputType)?("radio"===this.inputType&&!0===this.currentItem&&(this.currentItem=this.getCurrentItem()),c.hasClass(a,"checked")?"radio"!==this.inputType?c.removeClass(a,"checked"):c.hasClass(this.currentItem,"checked")||c.removeClass(a,"checked"):("radio"===this.inputType&&this.currentItem&&
c.removeClass(this.currentItem,"checked"),c.addClass(a,"checked"),this.currentItem=a)):c.hasClass(a,"action")&&(c.hasClass(a,"up")?b.previousElementSibling&&c.place(b,b.previousElementSibling,"before"):c.hasClass(a,"down")?b.nextElementSibling&&c.place(b,b.nextElementSibling,"after"):c.hasClass(a,"delete")&&(c.destroy(b),this.emit("editTable_itemChanged"))))},_getLabelFromCodevalue:function(a){for(var b=a,c=0;c<this.codedValues.length;c++){var d=this.codedValues[c];if(d.value===a){b=d.label;break}}return b},
_getCodeFromCodevalueLabel:function(a){for(var b=a,c=0;c<this.codedValues.length;c++){var d=this.codedValues[c];if(d.label===a){b=d.value;break}}return b},_createEmptyTarget:function(a){for(var b=this.emptyStr,e=this.emptyLabel?this.emptyLabel:b,d=" checked",f=0;f<a.length;f++)if(a[f].isChecked){d="";break}" checked"===d&&(this.currentItem=!0);var f='data\x3d"'+encodeURIComponent(b)+'"',g="",h=this.Nls.emptyValueTips;if(0===a.length||this.enableEmpty)g=" checked";return c.create("div",{"class":"item empty",
innerHTML:'\x3cdiv class\x3d"label name jimu-ellipsis" style\x3d"cursor: default;"'+f+"\x3e"+b+'\x3c/div\x3e\x3cdiv class\x3d"label alias jimu-ellipsis-Blanks" data\x3d"'+e+'"\x3e'+e+'\x3c/div\x3e\x3cdiv class\x3d"label '+this.inputType+d+' jimu-ellipsis"\x3e\x3c/div\x3e\x3cdiv class\x3d"label checkbox checkboxEmpty'+g+' jimu-ellipsis jimu-flipx" title\x3d"'+h+'"\x3e\x3c/div\x3e'},this.listContent)},_createTarget:function(a,b,e,d,f){var g="item";f&&(a=b=this.customValue,e=this.customLabel,g="item custom");
a=a||0===a?a:"";b=b||"";e=e?e:a;d=d?d:"";f=a;(this.codedValues||this.isNumberField)&&a!==this.Nls.addValuePlaceHolder&&(f=this.codedValues?this._getLabelFromCodevalue(a):b);a=this.isNumberField?a:encodeURIComponent(a);return c.create("div",{"class":g,innerHTML:'\x3cdiv class\x3d"label name jimu-ellipsis-Blanks" '+('data\x3d"'+a+'"')+"\x3e"+f+'\x3c/div\x3e\x3cdiv class\x3d"label alias jimu-ellipsis-Blanks" data\x3d"'+e+'"\x3e'+e+'\x3c/div\x3e\x3cdiv class\x3d"label '+this.inputType+d+' jimu-ellipsis"\x3e\x3c/div\x3e\x3cdiv class\x3d"actions jimu-float-trailing"\x3e\x3cdiv class\x3d"delete action jimu-float-trailing"\x3e\x3c/div\x3e\x3cdiv class\x3d"down action jimu-float-trailing"\x3e\x3c/div\x3e\x3cdiv class\x3d"up action jimu-float-trailing"\x3e\x3c/div\x3e\x3c/div\x3e'},
this.listContent)},_destroyTarget:function(a){for(var b=g(".item .name",this.listContent),e=0;e<b.length;e++){var d=b[e];if(l.get(this._dijit.domNode.parentNode,"innerHTML")===a){c.destroy(d.parentNode);break}}},getCurrentItem:function(){for(var a=g(".item .radio",this.listContent),b=0;b<a.length;b++){var e=a[b];if(c.hasClass(e,"checked"))return e}return null},_getEmptyLabel:function(){var a=g(".label.alias",this.listContent.firstChild)[0],b=this._getNodeText(a);a.children.length&&(b="Error"===this._dijit.state?
decodeURIComponent(c.getAttr(a,"data")):this._dijit.value);return b=h.sanitizeHTML(b)},_getEmptyStatus:function(){var a=g(".checkboxEmpty",this.listContent.firstChild)[0];return c.hasClass(a,"checked")?!0:!1},_getNodeText:function(a){return a.textContent||a.innerText||""},_setNodeText:function(a,b){a.innerHTML="\x26nbsp;";a.textContent?a.textContent=b:a.innerText=b},getListValues:function(){this.listItemsArray=[];this.listValuesArray=[];for(var a=g(".item .name",this.listContent),b="radio"===this.inputType?
1:0;b<a.length;b++){var e=a[b],d=h.getAncestorDom(e,function(a){return c.hasClass(a,"item")},3);if(!c.hasClass(d,"custom")){var d=this._getNodeText(e),f=decodeURIComponent(c.getAttr(e,"data"));if(this.isNumberField||this.codedValues)d=f;e.children.length&&(d="Error"===this._dijit.state?f:this._dijit.value,this.codedValues&&(d=this._getCodeFromCodevalueLabel(d),d=void 0!==d?d:f));d=this.isNumberField?parseFloat(d):h.sanitizeHTML(d);f=this._getNodeText(e.nextSibling);f===this.customLabel&&(f=d.toString(),
this.isNumberField&&(f=this._getLocalNumber(f)));e.nextSibling.children.length&&(f="Error"===this._dijit.state?decodeURIComponent(c.getAttr(e.nextSibling,"data")):this._dijit.value);f=h.sanitizeHTML(f);f={value:d,alias:f,isChecked:!1};this.listItemsArray.push(f);this.listValuesArray.push(d);c.hasClass(e.nextSibling.nextSibling,"checked")&&(f.isChecked=!0)}}a={list:this.listItemsArray,valueList:this.listValuesArray};"radio"===this.inputType&&(a.emptyLabel=this._getEmptyLabel(),a.enableEmpty=this._getEmptyStatus());
return a},setListValues:function(a,b){l.set(this.listContent,"innerHTML","");"radio"===this.inputType&&this._createEmptyTarget(a);for(var c=0;c<a.length;c++){var d=a[c],f="";d.isChecked&&(f=" checked",this.currentItem=!0);this._createTarget(d.value,b?b[c].label:d.value,d.alias,f)}},_initTable:function(){},getDijits:function(){return[this.mutiValuesSelect]},destroy:function(){this.inherited(arguments)}})});