// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/lang dojo/dom-class dojo/dom-geometry dojo/dom-style esri/tasks/query esri/geometry/geometryEngine esri/geometry/Polyline ./CSVUtils jimu/utils".split(" "),function(k,l,p,q,r,C,m,D,B,v){function w(a){return function(b,d){return b.attributes[a]<d.attributes[a]?-1:b.attributes[a]>d.attributes[a]?1:0}}return{getFields:function(a,b,d,e){var c=this.getSkipFields(a),g=[];if(!d&&b.advStat&&b.advStat.stats&&b.advStat.stats.outFields&&0<b.advStat.stats.outFields.length)k.forEach(b.advStat.stats.outFields,
function(a){g.push(a.expression)});else{if(a.infoTemplate)b=a.infoTemplate.info.fieldInfos;else if(0<e.map.itemInfo.itemData.operationalLayers.length){e=e.map.itemInfo.itemData.operationalLayers;b=null;var f=0;a:for(;f<e.length;f++){var h=e[f];if("ArcGISMapServiceLayer"===h.layerType&&"undefined"!==typeof h.layers)for(var n=0;n<h.layers.length;n++){var l=h.layers[n];if(l.id===a.layerId&&l.popupInfo){b=l.popupInfo.fieldInfos;break a}}}b||(b=a.fields)}else b=a.fields;if(b)for(e=0;e<b.length;e++)f=b[e],
d||"undefined"===typeof f.visible?(f=f.name?f.name:f.fieldName,-1===c.indexOf(f)&&g.push(f)):f.visible&&-1===c.indexOf(f.fieldName)&&g.push(f.fieldName)}a=this.getSpecialFields(a);return{dateFields:a.dateFields,specialFields:a.specialFields,typeIdField:a.typeIdField,types:a.types,fields:3<g.length&&!d?g.slice(0,3):g,allFields:g}},getField:function(a,b){for(var d=0;d<a.length;d++){var e=a[d];if(e.name===b||e.alias===b)return e}},getFieldValue:function(a,b,d,e,c,g,f,h,n){g=!1;f=b;d[a]&&"esriFieldTypeDate"===
d[a].type&&(g=!0,-1<Object.keys(e).indexOf(a)?(d=e[a],c="undefined"!==typeof d?{dateFormat:d}:{dateFormat:c}):c={dateFormat:c},f=v.fieldFormatter.getFormattedDate(new Date(b),c));!g&&h&&n&&(f=(a=v.getDisplayValueForCodedValueOrSubtype(h,a,n))&&a.hasOwnProperty("displayValue")?a.displayValue:f);return f},getSkipFields:function(a){var b=[];if(a.fields)for(var d=0;d<a.fields.length;d++){var e=a.fields[d];e&&e.type&&e.name&&"esriFieldTypeGeometry"===e.type&&b.push(e.name)}a.globalIdField&&""!==a.globalIdField&&
b.push(a.globalIdField);a.objectIdField&&""!==a.objectIdField&&b.push(a.objectIdField);return b},getSpecialFields:function(a){var b={},d=[];a.fields&&k.forEach(a.fields,l.hitch(this,function(e){if("esriFieldTypeDate"===e.type||e.domain||e.name===a.typeIdField){if("esriFieldTypeDate"===e.type&&a.infoTemplate)for(var c in a.infoTemplate._fieldsMap)"undefined"!==typeof a.infoTemplate._fieldsMap[c].fieldName&&a.infoTemplate._fieldsMap[c].fieldName===e.name&&a.infoTemplate._fieldsMap[c].format&&"undefined"!==
typeof a.infoTemplate._fieldsMap[c].format.dateFormat&&(d[e.name]=a.infoTemplate._fieldsMap[c].format.dateFormat);b[e.name]=e}}));return{specialFields:b,dateFields:d,typeIdField:a.typeIdField,types:a.types}},getSummaryFields:function(){},getPopupFields:function(a){var b=[];0<a.tabLayers.length&&k.forEach(a.tabLayers,l.hitch(this,function(a){var e=this.getSkipFields(a);"undefined"!==typeof a.popupInfo?k.forEach(a.popupInfo.fieldInfos,l.hitch(this,function(a){if(a.visible&&-1===e.indexOf(a.fieldName)){var c=
{value:0};c.expression=a.fieldName;c.label=a.label;b.push(c)}})):a.infoTemplate&&k.forEach(a.infoTemplate.info.fieldInfos,l.hitch(this,function(a){if(a.visible&&-1===e.indexOf(a.fieldName)){var c={value:0};c.expression=a.fieldName;c.label=a.label;b.push(c)}}))}));return b},getDisplayFields:function(a){var b;"undefined"!==typeof a.advStat&&"undefined"!==typeof a.advStat.stats&&"undefined"!==typeof a.advStat.stats.outFields?b=a.advStat.stats.outFields:(b=[],0<a.tabLayers.length&&k.forEach(a.tabLayers,
l.hitch(this,function(a){"undefined"!==typeof a.popupInfo?k.forEach(a.popupInfo.fieldInfos,l.hitch(this,function(a){if(a.visible){var c={value:0};c.expression=a.fieldName;c.label=a.label;b.push(c)}})):a.infoTemplate?k.forEach(a.infoTemplate.info.fieldInfos,l.hitch(this,function(a){if(a.visible){var c={value:0};c.expression=a.fieldName;c.label=a.label;b.push(c)}})):k.forEach((a.layerObject?a.layerObject:a).fields,l.hitch(this,function(a){var c={value:0};c.expression=a.name;c.label=a.alias;b.push(c)}))})));
return b},exportToCSV:function(a,b,d,e,c){if(0===a.length)return!1;var g=c.baseLabel,f=[],h=[];"proximity"===c.type&&a.sort(this.compareDistance);var n;"undefined"===typeof b.altKey?n=b:(n=!1,d=c.csvAllFields);k.forEach(a,l.hitch(this,function(a){"closest"===c.type&&delete a.attributes.DISTANCE;"proximity"===c.type&&(a.attributes.DISTANCE=this.getDistanceLabel(a.attributes.DISTANCE,c.unit,c.approximateLabel));f.push(a.attributes)}));if("summary"===c.type||"grouped"===c.type)if(!0===c.csvAllFields||
"true"===c.csvAllFields)for(var m in f[0])h.push(m);else for(a=0;a<c.summaryFields.length;a++)h.push(c.summaryFields[a].field);else for(var p in f[0])h.push(p);a=c.layer;m=a.fields;if(a&&a.loaded&&m||n){p=b?[]:this.getSkipFields(a);var t={};if(c.opLayers&&c.opLayers._layerInfos){var u=c.opLayers.getLayerInfoById(a.id);u&&(t.popupInfo=u.getPopupInfo())}var u=[],r=0;for(;r<h.length;r++){var q=h[r];if(-1===p.indexOf(q)){var v=!1,z,A=0;b:for(;A<m.length;A++)if(z=m[A],z.name===q){v=!0;break b}v?u.push(z):
u.push({name:q,alias:q,show:!0,type:"esriFieldTypeString"})}}t.datas=f;t.fromClient=!1;t.withGeometry=!1;t.outFields=u;t.formatDate=!0;t.formatCodedValue=!0;t.formatNumber=!1;var x=[],y=[];if(!b&&d&&"undefined"!==typeof e)switch(c.type){case "proximity":x.push(c.nlsCount);y.push(e);break;case "closest":var w=0;k.forEach(e,l.hitch(this,function(a){0===w&&(k.forEach(a,function(a){x.push(a.label)}),w+=1);var b=[];k.forEach(a,function(a){b.push(a.value)});y.push(b)}));break;case "summary":k.forEach(e,
l.hitch(this,function(a){var b=a.info.replace("\x3cbr/\x3e",""),e=!1,d=0;a:for(;d<c.calcFields.length;d++)if(b===c.calcFields[d].alias){e=!0;break a}e&&(x.push(b),y.push(a.total))}));break;case "grouped":k.forEach(e,function(a){x.push(a.info.replace("\x3cbr/\x3e",""));y.push(a.total)})}if(n)return{summaryLayer:a,details:u};B.exportCSVFromFeatureLayer(g,a,t);return{summaryLayer:a,details:{appendColumns:x,appendDatas:y,name:g,type:c.nlsValue}}}B.exportCSV(g,f,h)},isURL:function(a){return/(https?:\/\/|ftp:)/g.test(a)},
isEmail:function(a){return/\S+@\S+\.\S+/.test(a)},queryTabCount:function(){},performQuery:function(){},getFilter:function(a,b){var d="";b.traversal(function(b){if(a===b.id&&b.getFilter())return d=b.getFilter(),!0});return d},getGeoms:function(a){for(var b=[],d=[],e=0;e<a.length;e++){var c=a[e].geometry?a[e].geometry:a[e];if("polygon"===c.type&&-1===b.indexOf(e)){for(var g=0;g<a.length;g++)if(g!==e&&-1===b.indexOf(g)){var f=a[g].geometry?a[g].geometry:a[g];"polygon"===f.type?m.intersects(c,f)&&(b.push(g),
c=m.union(c,f)):b.push(g)}d.push(c)}}return d},createDefArray:function(a,b,d,e){for(var c=[],g=0;g<a.length;g++){var f=a[g];if(f){var h=new C;h.returnGeometry=!1;h.geometry=b;var n=-1===[null,void 0,""].indexOf(f.id)?f.id:e.layers;h.where=this.getFilter(n,d);"undefined"!==typeof f.queryCount?c.push(f.queryCount(h)):"undefined"!==typeof f.queryIds?c.push(f.queryIds(h)):"undefined"!==typeof f.queryFeatures&&c.push(f.queryFeatures(h))}}return c},updateTabCount:function(a,b,d,e,c){var g="undefined"!==
typeof c&&0<c?!0:!1;c=q.position(b).w;"undefined"!==typeof a&&0===a?(p.remove(b,"noFeatures"),p.remove(b,"noFeaturesActive"),p.add(b,g?"noFeaturesActive":"noFeatures")):(g&&p.contains(b,"noFeatures")&&p.remove(b,"noFeatures"),g&&p.contains(b,"noFeaturesActive")&&p.remove(b,"noFeaturesActive"));d&&(a="undefined"!==typeof a?e+" ("+v.localizeNumber(a).toString()+")":e,b.innerHTML=a);d=q.position(b).w;a=0;var f;d>c?(f=!0,a=d-c):c>d&&(f=!1,a=c-d);c=q.position(b.parentNode).w;if(0<c){f=f?c+a:c-a;r.set(b.parentNode,
"width",f+"px");b=b.parentNode.parentNode;c=b.parentNode;var h;if(c&&c.children&&0<c.children.length)for(a=0;a<c.children.length;a++)if(d=c.children[a],-1<d.className.indexOf("SA_panelRight")){h=d;break}h&&b&&(f>q.position(c).w?(r.set(b,"right","58px"),r.set(h,"display","block")):(r.set(b,"right","24px"),r.set(h,"display","none")))}},getDistanceLabel:function(a,b,d){return Math.round(100*a)/100+" "+b+" ("+d+")"},getSum:function(a,b){var d=0;k.forEach(a,function(a){d+=a.attributes[b]});return d},getMin:function(a,
b){a.sort(w(b));return a[0].attributes[b]},getMax:function(a,b){a.sort(w(b));a.reverse();return a[0].attributes[b]},getArea:function(a,b,d,e){var c=0;d=l.clone(d);d.miles=109413;d.kilometers=109414;d.feet=109405;d.meters=109404;d.yards=109442;d.nauticalMiles=109409;var g=d[e];k.forEach(a,function(a){for(var d=0;d<b.length;d++){var e=m.intersect(a.geometry,b[d]);null!==e&&(c+=m.geodesicArea(e,g))}});return c},getLength:function(a,b,d,e){var c=0,g=d[e];k.forEach(a,function(a){for(var d=0;d<b.length;d++){var e=
m.intersect(a.geometry,b[d]);null!==e&&(c+=m.geodesicLength(e,g))}});return c},getDistance:function(a,b,d){var e="point"!==a.type?a.getExtent().getCenter():a;b="point"!==b.type?b.getExtent().getCenter():b;e=new D([[e.x,e.y],[b.x,b.y]]);e.spatialReference=a.spatialReference;d="nauticalMiles"===d?"nautical-miles":d;return 4326===a.spatialReference.wkid||a.spatialReference.isWebMercator()?m.geodesicLength(e,d):m.planarLength(e,d)},compareDistance:function(a,b){return a.attributes.DISTANCE<b.attributes.DISTANCE?
-1:a.attributes.DISTANCE>b.attributes.DISTANCE?1:0}}});