// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Onglets",addTab:"Ajouter un onglet",layerName:"Couche",layerType:"Type d'analyse",layerLabel:"Etiquette",actions:"Actions",closest:"Entit\u00e9 la plus proche",proximity:"Proximit\u00e9",summary:"R\u00e9sum\u00e9",select_lbl:"-- S\u00e9lectionner --",general_setting_Label:"Param\u00e8tres g\u00e9n\u00e9raux",units_text_lbl:"Unit\u00e9s de distance",maximum_distance_lbl:"Distance maximale de l'entit\u00e9 la plus proche",
buffer_text_lbl:"Etiquette de la zone tampon",buffer_lbl:"Distance de la zone tampon",buffer_max_lbl:"Distance maximale de la zone tampon",buffer_min_lbl:"Distance minimale de la zone tampon",buffer_default_lbl:"Distance de la zone tampon par d\u00e9faut",not_less_than_max:"La distance doit \u00eatre inf\u00e9rieure \u00e0 la distance maximale de la zone tampon",not_between:"La distance doit \u00eatre comprise entre la distance minimale et maximale de la zone tampon.",not_more_than_min:"La distance doit \u00eatre sup\u00e9rieure \u00e0 la distance minimale de la zone tampon",
not_valid_number:"Doit \u00eatre un nombre valide",invalid_value:"La valeur ${type} n\u2019est pas valide",routing_checkBox:"Activer le calcul d'itin\u00e9raire",weather_Label:"Param\u00e8tres m\u00e9t\u00e9o",weather_checkBox:"Activer la m\u00e9t\u00e9o",weather_map_layers:"S\u00e9lectionner les couches m\u00e9t\u00e9orologiques...",selected_map_layers:" couches m\u00e9t\u00e9orologiques s\u00e9lectionn\u00e9es",instruction_weather:"Affichez les informations m\u00e9t\u00e9orologiques dans un volet.",
instruction_weather_layers:"Affichez d'autres couches m\u00e9t\u00e9orologiques.",instruction_weather_metric:"Affichez les valeurs standard/m\u00e9triques.",selectLayers:"S\u00e9lectionner les couches m\u00e9t\u00e9orologiques",weather_removed_message:"Les options m\u00e9t\u00e9orologiques ne sont plus disponibles pour ce widget.",currentlySelectedLayer:"S\u00e9lectionner dans les couches cartes",missingTabLabel:"L'\u00e9tiquette d'un onglet au moins est manquante",missingLayerInWebMap:"Aucune couche op\u00e9rationnelle n'a \u00e9t\u00e9 trouv\u00e9e.",
selectFields:"S\u00e9lectionner des champs",addField:"Ajouter un champ",sum:"Somme",min:"Minimal",max:"Maximal",avg:"Moyenne",count:"TOTAL",area:"SURFACE",length:"LONGUEUR",count_checkBox:"Afficher le nombre d\u2019entit\u00e9s",area_checkBox:"Afficher la somme de la surface",length_checkBox:"Afficher la somme des longueurs",max_records:"Limite maximale atteinte",save_label:"Options d'enregistrement",save_checkbox:"Activer l'enregistrement",report_label:"Options de rapport",report_checkbox:"Activer le rapport",
csv_label:"Options de CSV",csv_checkbox:"Exporter tous les champs",display_label:"Options d'affichage",display_checkbox:"Afficher les entit\u00e9s de synth\u00e8se",snapshot_label:"Options de vue fig\u00e9e",snapshot_checkbox:"Activer la vue fig\u00e9e",must_select_template:"S\u00e9lectionnez un des rapports de mise \u00e0 jour dans les options d'enregistrement.",count_label:"Etiquette de nombre",area_label:"Etiquette de zone",length_label:"Etiquette de longueur",invalid_string_width:"La valeur est trop longue. ",
layer_type_not_supported:"Type de couche non pris en charge",groupedSummary:"Nombres group\u00e9s",groupByField:"Champ Grouper par",labelType:"Ajouter une \u00e9tiquette",prefix:"En tant que pr\u00e9fixe",suffix:"En tant que suffixe",need_group_field:"Utilisez l'action de mise \u00e0 jour pour d\u00e9finir un champ Grouper par.",fieldTitle:"Champ",typeTitle:"Type",actionsTitle:"Actions",save_point_checkbox:"Enregistrer des points",save_line_checkbox:"Enregistrer des lignes",save_poly_checkbox:"Enregistrer des polygones",
no_valid_popup_fields:"Aucun champ valide dans la fen\u00eatre contextuelle. Utilisez l'action de mise \u00e0 jour pour d\u00e9finir un champ.",no_valid_fields:"Aucun champ valide. Utilisez l'action de mise \u00e0 jour pour d\u00e9finir des options d'affichage.",incident_label:"Etiquette de l'onglet",locate_incident_label:"Etiquette de la zone d'int\u00e9r\u00eat",incident:"Incident",locate_incident:"Localiser l'incident",buffer_value:"Distance de la zone tampon",tab_options:"Analyse",export_options:"Sortie",
instruction_save:"Enregistrez le lieu dans un service d'entit\u00e9s.",instruction_snapshot:"Cr\u00e9ez une carte web bas\u00e9e sur le lieu.",instruction_report:"Cr\u00e9ez un rapport imprim\u00e9 du lieu.",instruction_all_fields:"Exportez tous les champs avec t\u00e9l\u00e9chargement de fichier CSV.",data_label:"Param\u00e8tres de sortie des donn\u00e9es",layer_error:"Couche manquante ou non valide.",visibility_checkBox:"D\u00e9sactiver la gestion de la visibilit\u00e9 des couches",downloadTab:{reportLegend:"Param\u00e8tres du rapport",
textColorLabel:"S\u00e9lectionner une couleur pour les titres des colonnes",setButtonLabel:"D\u00e9finir",printGPServiceLabel:"URL du service d'impression",logoLabel:"Logo",logoChooserHint:"Cliquez sur l'ic\u00f4ne de l'image pour modifier l'image",footnoteLabel:"Note de bas de page"},_localized:{}}});