// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Kartice",addTab:"Dodaj karticu",layerName:"Sloj",layerType:"Vrsta analize",layerLabel:"Oznaka",actions:"Radnje",closest:"Najbli\u017ei geoobjekt",proximity:"Blizina",summary:"Sa\u017eetak",select_lbl:"-- Odaberi --",general_setting_Label:"Op\u0107e postavke",units_text_lbl:"Jedinice udaljenosti",maximum_distance_lbl:"Maksimalna udaljenost najbli\u017eeg geoobjekta",buffer_text_lbl:"Oznaka pojasa",buffer_lbl:"Veli\u010dina pojasa",
buffer_max_lbl:"Maksimalna udaljenost pojasa",buffer_min_lbl:"Minimalna udaljenost pojasa",buffer_default_lbl:"Zadana udaljenost pojasa",not_less_than_max:"Udaljenost mora biti manja od maksimalne udaljenosti pojasa",not_between:"Udaljenost mora biti izme\u0111u minimalne i maksimalne udaljenosti pojasa",not_more_than_min:"Udaljenost mora biti ve\u0107a od minimalne udaljenosti pojasa",not_valid_number:"Mora biti valjani broj",invalid_value:"Vrijednost ${type} nije va\u017ee\u0107a",routing_checkBox:"Omogu\u0107i preusmjeravanje",
weather_Label:"Postavke vremena",weather_checkBox:"Omogu\u0107i vrijeme",weather_map_layers:"Odaberi sloj s vremenom...",selected_map_layers:" odabrani slojevi s vremenom",instruction_weather:"Prika\u017ei informacije o vremenu u plo\u010di.",instruction_weather_layers:"Prika\u017ei dodatne slojeve s vremenom.",instruction_weather_metric:"Prika\u017ei standardne/metarske vrijednosti.",selectLayers:"Odaberi slojeve s vremenom",weather_removed_message:"Opcije vremena vi\u0161e nisu dostupne za ovaj widget.",
currentlySelectedLayer:"Odaberi iz slojeva karte",missingTabLabel:"Barem jedna kartica nema svoju oznaku",missingLayerInWebMap:"Nema operativnih slojeva.",selectFields:"Odaberi polja",addField:"Dodaj polje",sum:"Zbroj",min:"Minimum",max:"Maksimum",avg:"Prosje\u010dno",count:"BROJ",area:"PODRU\u010cJE",length:"DULJINA",count_checkBox:"Prika\u017ei broj geoobjekata",area_checkBox:"Prika\u017ei zbroj podru\u010dja",length_checkBox:"Prika\u017ei zbroj duljina",max_records:"Dosegnuto je maksimalno ograni\u010denje",
save_label:"Opcije spremanja",save_checkbox:"Omogu\u0107i spremanje",report_label:"Opcije izvje\u0161\u0107a",report_checkbox:"Omogu\u0107i izvje\u0161\u0107e",csv_label:"Opcije CSV-a",csv_checkbox:"Izvezi sva polja",display_label:"Opcije prikaza",display_checkbox:"Prika\u017ei geoobjekte sa\u017eetka",snapshot_label:"Opcije snimke",snapshot_checkbox:"Omogu\u0107i snimku",must_select_template:"Odaberite jedan od predlo\u017eaka za ure\u0111ivanje u opcijama za spremanje.",count_label:"Oznaka zbroja",
area_label:"Oznaka podru\u010dja",length_label:"Oznaka du\u017eine",invalid_string_width:"Vrijednost je preduga\u010dka. ",layer_type_not_supported:"Vrsta sloja nije podr\u017eana",groupedSummary:"Grupirani zbrojevi",groupByField:"Grupiraj po polju",labelType:"Pridodaj oznaku",prefix:"Kao prefiks",suffix:"Kao sufiks",need_group_field:"Upotrijebite radnju ure\u0111ivanja za odre\u0111ivanje grupe po polju.",fieldTitle:"Polje",typeTitle:"Vrsta",actionsTitle:"Radnje",save_point_checkbox:"Spremi to\u010dke",
save_line_checkbox:"Spremi linije",save_poly_checkbox:"Spremi poligone",no_valid_popup_fields:"Nema valjanih polja u sko\u010dnom prozoru. Upotrijebite radnju ure\u0111ivanja za odre\u0111ivanje polja.",no_valid_fields:"Nema valjanih polja. Upotrijebite radnju ure\u0111ivanja za odre\u0111ivanje opcija prikaza.",incident_label:"Oznaka kartice",locate_incident_label:"Oznaka podru\u010dja interesa",incident:"Incident",locate_incident:"Prona\u0111i incident",buffer_value:"Veli\u010dina pojasa",tab_options:"Analiza",
export_options:"Izlaz",instruction_save:"Spremite lokaciju u uslugu geoobjekta.",instruction_snapshot:"Stvorite web kartu na temelju lokacije.",instruction_report:"Stvorite ispisano izvje\u0161\u0107e o lokaciji.",instruction_all_fields:"Izvezite sva polja s CSV preuzimanjem.",data_label:"Postavke izlaza podataka",layer_error:"Sloj nedostaje ili nije va\u017ee\u0107i.",visibility_checkBox:"Onemogu\u0107i upravljanje vidljivosti sloja",downloadTab:{reportLegend:"Postavke izvje\u0161\u0107a",textColorLabel:"Odaberite boju za nazive stupaca",
setButtonLabel:"Postavi",printGPServiceLabel:"URL usluge ispisa",logoLabel:"Logotip",logoChooserHint:"Kliknite na ikonu slike za promjenu slike",footnoteLabel:"Fusnota"},_localized:{}}});