// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Zavihki",addTab:"Dodaj zavihek",layerName:"Sloj",layerType:"Tip analize",layerLabel:"Napis",actions:"Dejanja",closest:"Najbli\u017eji geoobjekt",proximity:"Bli\u017eina",summary:"Povzetek",select_lbl:"-- Izberite --",general_setting_Label:"Splo\u0161ne nastavitve",units_text_lbl:"Enote razdalje",maximum_distance_lbl:"Maksimalna razdalja najbli\u017ejega geoobjekta",buffer_text_lbl:"Napis obrisa",buffer_lbl:"Razdalja obrisa",
buffer_max_lbl:"Maksimalna razdalja obrisa",buffer_min_lbl:"Minimalna razdalja obrisa",buffer_default_lbl:"Privzeta razdalja obrisa",not_less_than_max:"Razdalja mora biti manj\u0161a od maksimalne razdalje obrisa",not_between:"Razdalja mora biti med minimalno in maksimalno razdaljo obrisa",not_more_than_min:"Razdalja mora biti ve\u010dja od minimalne razdalje obrisa",not_valid_number:"Mora biti veljavno \u0161tevilo",invalid_value:"${type} vrednost je neveljavna",routing_checkBox:"Omogo\u010di usmerjanje",
weather_Label:"Nastavitve vremena",weather_checkBox:"Omogo\u010di vreme",weather_map_layers:"Izberite vremenske sloje...",selected_map_layers:" vremenski sloji izbrani",instruction_weather:"Informacije o vremenu prika\u017ei na plo\u0161\u010di.",instruction_weather_layers:"Prika\u017ei dodatne vremenske sloje.",instruction_weather_metric:"Prika\u017ei standardne/metri\u010dne vrednosti.",selectLayers:"Izberite vremenske sloje",weather_removed_message:"Mo\u017enosti vremena niso ve\u010d na voljo za ta pripomo\u010dek.",
currentlySelectedLayer:"Izberite iz kartnih slojev",missingTabLabel:"Vsaj enemu zavihku manjka napis",missingLayerInWebMap:"Operativnih slojev ni mogo\u010de najti.",selectFields:"Izberite polja",addField:"Dodaj polje",sum:"Vsota",min:"Minimum",max:"Maksimum",avg:"Povpre\u010dje",count:"\u0160TETJE",area:"POVR\u0160INA",length:"\u0160TETJE",count_checkBox:"POVR\u0160INA",area_checkBox:"Prikaz vsote povr\u0161in",length_checkBox:"Prikaz vsote dol\u017ein",max_records:"Maksimalna dose\u017eena omejitev",
save_label:"Mo\u017enosti shranjevanja",save_checkbox:"Omogo\u010di shranjevanje",report_label:"Mo\u017enosti poro\u010dila",report_checkbox:"Omogo\u010di poro\u010dilo",csv_label:"Mo\u017enosti CSV",csv_checkbox:"Izvozi vsa polja",display_label:"Mo\u017enosti prikaza",display_checkbox:"Prikaz povzetka geoobjektov",snapshot_label:"Mo\u017enosti posnetka",snapshot_checkbox:"Omogo\u010di posnetek",must_select_template:"Izberite eno od predlog za urejanja v mo\u017enostih shranjevanja.",count_label:"Napis \u0161tetja",
area_label:"Napis povr\u0161ine",length_label:"Napis dol\u017eine",invalid_string_width:"Vrednost je predolga. ",layer_type_not_supported:"Tip sloja ni podprt",groupedSummary:"Zdru\u017eeni se\u0161tevki",groupByField:"Zdru\u017ei po polju",labelType:"Dodaj napis",prefix:"Kot predpono",suffix:"Kot pripono",need_group_field:"Uporabite urejanje za dolo\u010danje skupine po polju.",fieldTitle:"Polje",typeTitle:"Tip",actionsTitle:"Dejanja",save_point_checkbox:"Shrani to\u010dke",save_line_checkbox:"Shrani linije",
save_poly_checkbox:"Shrani poligone",no_valid_popup_fields:"V pojavnem oknu ni veljavnih polj. Uporabite urejanje za dolo\u010danje polja.",no_valid_fields:"Ni veljavnih polj. Uporabite urejanje za dolo\u010danje mo\u017enosti prikaza.",incident_label:"Napis zavihka",locate_incident_label:"Napis interesnega obmo\u010dja",incident:"Incident",locate_incident:"Lociraj incident",buffer_value:"Razdalja obrisa",tab_options:"Analiza",export_options:"Rezultat",instruction_save:"Shranite lokacijo v geoobjektno storitev.",
instruction_snapshot:"Ustvarite spletno karto na osnovi lokacije.",instruction_report:"Ustvarite natisnjeno poro\u010dilo lokacije.",instruction_all_fields:"Izvozi vsa polja s prenosom CSV.",data_label:"Nastavitve izpisa podatkov",layer_error:"Sloj manjka ali ni veljaven.",visibility_checkBox:"Onemogo\u010di upravljanje vidnosti sloja",downloadTab:{reportLegend:"Nastavitve poro\u010dila",textColorLabel:"Izberi barvo za naslove stolpcev",setButtonLabel:"Nastavi",printGPServiceLabel:"URL storitve tiskanja",
logoLabel:"Logotip",logoChooserHint:"Kliknite ikono za zamenjavo slike",footnoteLabel:"Sprotna opomba"},_localized:{}}});