// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred dojo/query ./utils dijit/form/Button dijit/_TemplatedMixin dijit/_WidgetBase esri/undoManager esri/OperationBase esri/graphic esri/tasks/query esri/tasks/QueryTask esri/tasks/RelationshipQuery esri/layers/FeatureLayer esri/dijit/AttributeInspector esri/dijit/Popup esri/dijit/PopupTemplate jimu/portalUrlUtils jimu/SelectionManager jimu/ConfigManager jimu/dijit/DropdownMenu jimu/dijit/LoadingIndicator jimu/LayerInfos/LayerInfos".split(" "),
function(q,d,m,g,n,k,r,p,y,z,A,B,C,u,t,v,D,E,F,G,H,w,x,I,J,K,L){var h=q([A,z],{baseClass:"related-records-editor",templateString:"\x3cdiv\x3e\x3cdiv class\x3d'operation-box' data-dojo-attach-point\x3d'operationBox'\x3e\x3cdiv class\x3d'previos-btn feature-action' data-dojo-attach-point\x3d'previouBtn'data-dojo-attach-event\x3d'click:_onPreviouBtnClick'\x3e\x3c/div\x3e\x3cdiv class\x3d'operation-title' data-dojo-attach-point\x3d'operationTitle'\x3e\x3c/div\x3e\x3cdiv class\x3d'add-new-btn' data-dojo-attach-point\x3d'addNewBtn'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'content-box' data-dojo-attach-point\x3d'contentBox'\x3e\x3c/div\x3e\x3c/div\x3e",
editorATI:null,originalFeature:null,originalLayer:null,originalJimuLayerInfo:null,layerInfosObj:null,undoManager:null,refDomNode:null,_temporaryData:null,tableInfosParam:null,postCreate:function(){this._init();g.place(this.domNode,this.refDomNode,"after");window.isRTL?g.addClass(this.previouBtn,"icon-arrow-forward"):g.addClass(this.previouBtn,"icon-arrow-back");this.loading=(new K({hidden:!0})).placeAt(this.domNode);this._clearPage();this.showFirstPage({feature:this.originalFeature,oriJimuLayerInfo:this.originalJimuLayerInfo})},
_init:function(){this.refDomNode=this.editorATI.domNode;this.originalLayer=this.originalFeature.getLayer();this.layerInfosObj=L.getInstanceSync();this.originalJimuLayerInfo=this.layerInfosObj.getLayerOrTableInfoById(this.originalLayer.id);this.undoManager=new B;this._temporaryData={eventHandles:[],dijits:[]};this._tempPopup=new G({},g.create("div"));this._tempPopup.show()},destroy:function(){this._clearPage();this._tempPopup.destroy();this.inherited(arguments)},_getRelatedTableInfoArray:function(a){var b=
new k,c=[];a.getRelatedTableInfoArray("esriRelRoleOrigin").then(d.hitch(this,function(a){m.forEach(a,function(a){this._findTableInfoFromTableInfosParam(a)&&c.push(a)},this);b.resolve(c)}));return b},_getRelatedRecordsByQuery:function(a){var b=new k,c=new t,e=new v(a.destJimuLayerInfo.getUrl()),f=a.destJimuLayerInfo.layerObject.relationships.keyField,l=a.oriJimuLayerInfo.layerObject.objectIdField;c.where=f?f+" \x3d "+a.feature.attributes[f]:l+" \x3d "+a.feature.attributes[l];c.outFields=["*"];e.execute(c,
d.hitch(this,function(a){b.resolve(a)}));return b},_getRelatedRecordsByRelatedQuery:function(a){var b=new k,c=new D,e=this._getOriRelationshipByDestLayer(a);c.outFields=["*"];c.relationshipId=e.id;var f=a.feature.attributes[a.oriJimuLayerInfo.layerObject.objectIdField];c.objectIds=[f];c.definitionExpression=a.destJimuLayerInfo.getFilter();a.oriJimuLayerInfo.layerObject.queryRelatedFeatures(c,d.hitch(this,function(a){(a=a[f]&&a[f].features)?b.resolve(a):b.resolve([])}),d.hitch(this,function(){b.resolve([])}));
return b},_getOriRelationshipByDestLayer:function(a){var b=null;m.some(a.oriJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.destJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_getDestRelationshipByDestLayer:function(a){var b=null;m.some(a.destJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.oriJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_createATI:function(a){var b;b=a.destJimuLayerInfo;var c=null,e,f=this._findTableInfoFromTableInfosParam(b);
f&&(c=new h.ATI({layerInfos:[f],hideNavButtons:!0},g.create("div")),c.startup(),this._temporaryData.dijits.push(c),e=this._findTableInfoFromTableInfosParam(b),(e=p.getEditCapabilities(b.layerObject,e).canDelete)||r(".atiButton.atiDeleteButton",c.domNode).addClass("hidden"));this._editWidget._configEditor.usingSaveButton&&(b=c.addButton(this.nls.save,"save-button related-record disable","after"),b=n(b,"click",d.hitch(this,this._onSaveBtnClick,a,c)),this._temporaryData.eventHandles.push(b));b=c.addButton(this.nls.close,
"close-button related-record","before");b=n(b,"click",d.hitch(this,this._onCloseBtnClick));this._temporaryData.eventHandles.push(b);e&&(b=n(c,"delete",d.hitch(this,this._onDeleteBtnClick,a)),this._temporaryData.eventHandles.push(b));b=n(c,"attribute-change",d.hitch(this,this._onAttributeChange,a));this._temporaryData.eventHandles.push(b);return c},_findTableInfoFromTableInfosParam:function(a){var b=null;m.some(this.tableInfosParam,function(c){if(c.featureLayer.id===a.id)return b=c,!0},this);return b},
_keepReferentialIntegrity:function(a){var b=this._getOriRelationshipByDestLayer(a),c=this._getDestRelationshipByDestLayer(a),e,f,d={key:"",value:"",hasRelationshipTable:!1,originKeyFieldInRelationshipTable:"",originValueInRelationshipTable:"",destKeyFieldInRelationshipTable:"",destValueInRelationshipTable:""};b.keyField&&c&&c.keyField?(e=p.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,b.keyField),f=p.ignoreCaseToGetFieldKey(a.destJimuLayerInfo.layerObject,c.keyField),e&&f&&(d.key=f,d.value=
a.feature.attributes[e])):b.keyField&&(e=p.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,b.keyField))&&(d.key=e,d.value=a.feature.attributes[e]);b&&null!=b.relationshipTableId&&c&&null!=c.relationshipTableId&&(d.hasRelationshipTable=!0,d.originKeyFieldInRelationshipTable=b.keyFieldInRelationshipTable,d.destKeyFieldInRelationshipTable=c.keyFieldInRelationshipTable,d.originValueInRelationshipTable=a.feature.attributes[e],a.relatedFeature&&(d.destValueInRelationshipTable=a.relatedFeature.attributes[f||
e]));return d},_prepareNewRelatedRecord:function(a){var b=this._getTemplateFromLayerObject(a.destJimuLayerInfo.layerObject),b=d.mixin({},b?b.prototype.attributes:{});a=this._keepReferentialIntegrity(a);a.hasRelationshipTable||(b[a.key]=a.value);return new u(null,null,b,null)},_prepareNewRelationshipRecord:function(a,b){var c=null,d={};a=this._keepReferentialIntegrity(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b));a.hasRelationshipTable&&(d[a.originKeyFieldInRelationshipTable]=
a.originValueInRelationshipTable,d[a.destKeyFieldInRelationshipTable]=a.destValueInRelationshipTable,c=new u(null,null,d,null));return c},_prepareRelationshipTableInfo:function(a){var b=this._getOriRelationshipByDestLayer(a).relationshipTableId,c=null;if(null==b)return null;a=a.oriJimuLayerInfo.layerObject;var e=a.url.lastIndexOf("/"),f=a.url.slice(0,e)+"/"+b.toString();m.some(this.tableInfosParam,function(a){if(d.getObject("featureLayer.url",!1,a)&&w.removeProtocol(f.toString().toLowerCase()).replace(/\/+/g,
"/")===w.removeProtocol(a.featureLayer.url.toString().toLowerCase()).replace(/\/+/g,"/"))return c=this.layerInfosObj.getLayerOrTableInfoById(a.featureLayer.id),!0},this);return c},_addNewRelationshipReocrd:function(a,b){var c=new k,e=null;(a=this._prepareNewRelationshipRecord(b,a))&&(e=this._prepareRelationshipTableInfo(b));e&&e.layerObject?e.layerObject.applyEdits([a],null,null,d.hitch(this,function(){c.resolve()}),d.hitch(this,function(){console.warn("Failed to add relationship record.");c.resolve()})):
c.resolve();return c},_addNewRelatedRecord:function(a,b){var c=new k,e=b.destJimuLayerInfo.layerObject;e.applyEdits([a],null,null,d.hitch(this,function(f){var l=f[0];if(l.success&&l.objectId){f=new t;var g=new v(e.url);f.where=e.objectIdField+" \x3d "+l.objectId;f.outFields=["*"];g.execute(f,d.hitch(this,function(f){var g=f.features[0];g||(a.attributes[e.objectIdField]=l.objectId,g=a);this._addNewRelationshipReocrd(g,b).then(d.hitch(this,function(){c.resolve(g)}))}),d.hitch(this,function(){c.reject()}))}else c.reject()}),
d.hitch(this,function(){c.reject()}));return c},_deleteRelatedRecord:function(a){var b=new k;a.destJimuLayerInfo.layerObject.applyEdits(null,null,[a.relatedFeature],d.hitch(this,function(){b.resolve()}),d.hitch(this,function(){b.reject()}));return b},_updateRelatedRecordOnSave:function(a){this.loading.show();this._updateRelatedRecord(a).then(d.hitch(this,function(){this.loading.hide()}),d.hitch(this,function(){this.loading.hide()}))},_updateRelatedRecordOnClient:function(a,b){this._editWidget._startEditingSession();
a.relatedFeature.attributes[b.fieldName]=b.fieldValue;var c=b.target;c&&c.updateCurrentSelectdFeature&&c.updateCurrentSelectdFeature([a.relatedFeature],a.destJimuLayerInfo.layerObject,b.fieldName,b.fieldValue)},_updateRelatedRecordDirectly:function(a,b){this.loading.show();a.relatedFeature.attributes[b.fieldName]=b.fieldValue;this._updateRelatedRecord(a).then(d.hitch(this,function(){this.loading.hide();var c=b.target;c&&c.updateCurrentSelectdFeature&&c.updateCurrentSelectdFeature([a.relatedFeature],
a.destJimuLayerInfo.layerObject,b.fieldName,b.fieldValue)}),d.hitch(this,function(){this.loading.hide()}))},_updateRelatedRecord:function(a){var b=new k;a.destJimuLayerInfo.layerObject.applyEdits(null,[a.relatedFeature],null,d.hitch(this,function(){b.resolve()}),d.hitch(this,function(){b.reject()}));return b},_getDisplayTitleOfRelatedRecord:function(a,b,c){var d=a.getInfoTemplate();return(a="popupTitle"===c&&d?"function"===typeof d.title?d.title(b):d.title:this._getDisplayTitleFromPopup(a,b,c))?a:
""},_getDisplayTitleFromPopup:function(a,b,c){(a=this._getPopupTemplateWithOnlyDisplayField(a,c))?(b.setInfoTemplate(a),this._tempPopup.setFeatures([b]),c=(c=r("td.attrValue",this._tempPopup.domNode)[0])&&c.innerHTML,b.setInfoTemplate(null)):c=p.getAttrByFieldKey(b,c);return c},_getPopupTemplateWithOnlyDisplayField:function(a,b){a=a._getCustomPopupInfo(a.layerObject,[b]);return new H(a)},_getTemplateFromLayerObject:function(a){var b=null;a.templates&&a.templates[0]?b=a.templates[0]:a.types&&a.types[0]&&
a.types[0].templates[0]&&(b=a.types[0].templates[0]);return b},showRelatedRecords:function(a){this._changeRefDomNode();var b=d.getObject("_wabProperties.originalLayerName",!1,a.destJimuLayerInfo.layerObject)||a.destJimuLayerInfo.title;this._setOperationTitle(b);this._clearPage();this.loading.show();this._getRelatedRecordsByRelatedQuery(a).then(d.hitch(this,function(b){this._showAddNewBtn(a);0<b.length?this._setTitle(window.jimuNls.popup.relatedRecords):this._setTitle(window.jimuNls.popup.noRelatedRecotds,
"font-normal");var c=this._showFieldSelector(a.destJimuLayerInfo);m.forEach(b,function(b,e){b._layer=a.destJimuLayerInfo.layerObject;var f=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,b,c);e=g.create("div",{"class":"item record-item enable "+(0===e%2?"oddLine":"evenLine"),innerHTML:f},this.contentBox);e.relatedRecord=b;e=n(e,"click",d.hitch(this,function(){this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,
b))}));this._temporaryData.eventHandles.push(e)},this);this.loading.hide()}))},showInspector:function(a){var b=!1;this._changeRefDomNode();var c=a.destJimuLayerInfo.layerObject,e=d.getObject("_wabProperties.originalLayerName",!1,c)||a.destJimuLayerInfo.title,c=d.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,c),f=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,a.relatedFeature,c);"popupTitle"!==c&&(f=e+": "+f);this._setOperationTitle(f);this._clearPage();(f=this._createATI(a))&&
g.place(f.domNode,this.contentBox);e=a.destJimuLayerInfo.layerObject.objectIdField;c=a.relatedFeature.attributes[e];null===c||void 0===c?(f.showFeature(a.relatedFeature,a.destJimuLayerInfo.layerObject),b=!0,r(".atiButton.atiDeleteButton",f.domNode).addClass("disable"),this._editWidget._startEditingSession()):(this.loading.show(),f=new t,f.where=e+" \x3d "+c,a.destJimuLayerInfo.layerObject.selectFeatures(f,E.SELECTION_NEW,d.hitch(this,function(){this.loading.hide();var b=a.destJimuLayerInfo.layerObject.getSelectedFeatures();
b&&b[0]&&b[0].geometry&&this._activeGraphicEdit(b[0],a.oriJimuLayerInfo)})));this.showRelatedTables(this._createOperationData(a.relatedFeature,a.destJimuLayerInfo,null,null),a,b)},showRelatedTables:function(a,b,c){this._getRelatedTableInfoArray(a.oriJimuLayerInfo).then(d.hitch(this,function(e){0<e.length&&this._setTitle(window.jimuNls.popup.relatedTables);m.forEach(e,function(e,l){l=g.create("div",{"class":"item table-item "+(0===l%2?"oddLine ":"evenLine ")+(c?"disable ":"enable "),innerHTML:e.title},
this.contentBox);c||(l=n(l,"click",d.hitch(this,function(){var c;this._editWidget._configEditor.usingSaveButton?c=this._editWidget._popupConfirmDialog():(c=new k,c.resolve(!0));c.then(d.hitch(this,function(c){c&&e.getLayerObject().then(d.hitch(this,function(){b?this._addOperation(h.OPERATION_SHOW_INSPECTOR,b):this._addOperation(h.OPERATION_FIRST,a);this.showRelatedRecords(this._createOperationData(a.feature,a.oriJimuLayerInfo,e,null))}))}))})),this._temporaryData.eventHandles.push(l))},this)}))},
showFirstPage:function(a,b){this._clearPage();this._revertRefDomNode();this.showRelatedTables(a);b&&(m.forEach(this._editWidget._jimuLayerInfos.getLayerInfoArray(),function(a){a.layerObject&&a.layerObject.clearSelection&&a.id!==this.originalJimuLayerInfo.id&&x.getInstance().clearSelection(a.layerObject)},this),this.originalFeature.setSymbol(this.originalLayer.getSelectionSymbol()),this._activeGraphicEdit(this.originalFeature))},_activeGraphicEdit:function(a,b){b&&(b.id===this.originalJimuLayerInfo.id?
this.originalFeature.setSymbol(null,!0):x.getInstance().clearSelection(b.layerObject));var c;this._editWidget.editor._editVertices=!0;this._editWidget.editor._activateEditToolbar(a);a.geometry&&(c="point"===a.geometry.type?a.geometry:a.geometry.getExtent().getCenter());this._editWidget.map.infoWindow.show(c)},_createOperationData:function(a,b,c,d){return{feature:a,oriJimuLayerInfo:b,destJimuLayerInfo:c,relatedFeature:d}},_addOperation:function(a,b){this.undoManager.add(new h.Operation(a,b,this))},
_onPreviouBtnClick:function(){var a;this._editWidget._configEditor.usingSaveButton?a=this._editWidget._popupConfirmDialog():(a=new k,a.resolve(!0));a.then(d.hitch(this,function(a){a&&this.undoManager.undo()}))},_onAddNewBtnClick:function(a){var b=a.destJimuLayerInfo.layerObject,c=this._prepareNewRelatedRecord(a),e=this._keepReferentialIntegrity(a);"Table"!==b.type?this._editWidget._startEditingRelatedGraphic(a,e):this._editWidget._configEditor.usingSaveButton?(this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,
a),this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,c))):(this.loading.show(),this._addNewRelatedRecord(c,a).then(d.hitch(this,function(b){this.loading.hide();this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}),d.hitch(this,function(){this.loading.hide()})))},_onCloseBtnClick:function(){this._editWidget.editPopup.hide()},_onDeleteBtnClick:function(a){var b=
a.relatedFeature.attributes[a.destJimuLayerInfo.layerObject.objectIdField];null!==b&&void 0!==b&&(this._editWidget._configEditor.usingSaveButton&&this._editWidget._stopEditingSession(),this.loading.show(),this._deleteRelatedRecord(a).then(d.hitch(this,function(){this.loading.hide();this._onPreviouBtnClick()}),d.hitch(this,function(){this.loading.hide()})))},_onSaveBtnClick:function(a){if(this._editWidget._isEditingSession){var b=a.relatedFeature.attributes[a.destJimuLayerInfo.layerObject.objectIdField];
null===b||void 0===b?(b=a.relatedFeature,this.loading.show(),this._addNewRelatedRecord(b,a).then(d.hitch(this,function(b){this.loading.hide();this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}),d.hitch(this,function(){this.loading.hide()}))):this._updateRelatedRecordOnSave(a);this._editWidget._stopEditingSession()}},_onAttributeChange:function(a,b){this._editWidget._configEditor.usingSaveButton?this._updateRelatedRecordOnClient(a,b):this._updateRelatedRecordDirectly(a,
b)},_clearPage:function(){g.empty(this.contentBox);g.setStyle(this.addNewBtn,"display","none");m.forEach(this._temporaryData.eventHandles,function(a){a&&a.remove&&a.remove()},this);this._temporaryData.eventHandles=[];m.forEach(this._temporaryData.dijits,function(a){a&&a.destroy&&a.destroy()},this);this._temporaryData.dijits=[]},_changeRefDomNode:function(){g.setStyle(this.refDomNode,"display","none");g.setStyle(this.operationBox,"display","block");g.addClass(this.domNode,"fix-height-mode");this.previouBtn.title=
window.jimuNls.common.back;this.addNewBtn.title=window.jimuNls.common.newText;this.undoManager.peekUndo()?g.setStyle(this.previouBtn,"display","block"):g.setStyle(this.previouBtn,"display","none")},_revertRefDomNode:function(){g.setStyle(this.refDomNode,"display","block");g.setStyle(this.operationBox,"display","none");g.removeClass(this.domNode,"fix-height-mode")},_showAddNewBtn:function(a){var b=a.destJimuLayerInfo.layerObject,c=this._findTableInfoFromTableInfosParam(a.destJimuLayerInfo);p.getEditCapabilities&&
p.getEditCapabilities(b,c).canCreate&&(g.setStyle(this.addNewBtn,"display","block"),a=n(this.addNewBtn,"click",d.hitch(this,this._onAddNewBtnClick,a)),this._temporaryData.eventHandles.push(a))},_setTitle:function(a,b){a&&g.create("div",{"class":"title-box "+(b?b:""),innerHTML:a},this.contentBox)},_setOperationTitle:function(a){g.setAttr(this.operationTitle,"innerHTML",a);g.setAttr(this.operationTitle,"title",a)},_showFieldSelector:function(a){var b="objecid",c=r(".title-box",this.contentBox)[0],e=
a.layerObject,f=[];if(!c||!a)return b;var g=a.getPopupInfo();g&&g.title&&f.push({label:window.jimuNls.popup.saveAsPopupTitle,value:"popupTitle"});var h=this._findTableInfoFromTableInfosParam(a);h&&h.fieldInfos&&m.forEach(h.fieldInfos,function(a){"globalid"!==a.fieldName.toLowerCase()&&"shape"!==a.fieldName.toLowerCase()&&f.push({label:a.label||a.fieldName,value:a.fieldName})});c=(new J({items:f})).placeAt(c);c.domNode.title=window.jimuNls.popup.chooseFieldTip;var h=d.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",
!1,e),k=p.ignoreCaseToGetFieldObject(a.layerObject,a.layerObject.displayField||a.layerObject.objectIdField),q=I.getInstance().getAppConfig();h?b=h:"2.3"===q.configWabVersion&&k&&k.name?b=k.name:g&&g.title?b="popupTitle":k&&k.name?b=k.name:0<f.length&&(b=f[0].value);b&&(c.setHighlightValue(b),d.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,e));this._temporaryData.dijits.push(c);a=n(c,"click-item",d.hitch(this,function(a,b){r(".item.record-item",this.contentBox).forEach(d.hitch(this,
function(c){d.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,e);var f=this._getDisplayTitleOfRelatedRecord(a,c.relatedRecord,b);c.innerHTML=f}))},a));this._temporaryData.eventHandles.push(a);return b}});h.Operation=q([C],{constructor:function(a,b,c){this.operationName=a;this.operationData=b;this.relatedRecordsEditor=c},performUndo:function(){switch(this.operationName){case h.OPERATION_SHOW_RELATED_TABLES:return this.relatedRecordsEditor.showRelatedTables(this.operationData);
case h.OPERATION_SHOW_RELATED_RECORDS:return this.relatedRecordsEditor.showRelatedRecords(this.operationData);case h.OPERATION_SHOW_INSPECTOR:return this.relatedRecordsEditor.showInspector(this.operationData);default:return this.relatedRecordsEditor.showFirstPage(this.operationData,!0)}}});h.ATI=q([F],{constructor:function(){this._aiConnects=[];this._selection=[];this._toolTips=[]},addButton:function(a,b,c){c=c?c:"before";a=new y({label:a,"class":" atiButton "+b},g.create("div"));g.place(a.domNode,
this.deleteBtn.domNode,c);return a},updateCurrentSelectdFeature:function(a,b,c,d){this._selection&&this._selection[0]&&c&&(this._selection[0].attributes[c]=d,b.ownershipBasedAccessControlForFeatures=!0,this.refresh(),b.ownershipBasedAccessControlForFeatures=!1)},_getFields:function(a){return a.fields}});d.mixin(h,{OPERATION_SHOW_RELATED_TABLES:"showRelatedTables",OPERATION_SHOW_RELATED_RECORDS:"showRelatedRecords",OPERATION_SHOW_INSPECTOR:"showInspector",OPERATION_FIRST:"first"});return h});