// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Evented dojo/_base/array dojo/_base/html dojo/_base/fx dojo/on dojo/sniff dojo/touch dojo/query dojo/dnd/move dijit/_WidgetBase jimu/utils".split(" "),function(r,e,t,f,b,q,h,u,v,n,w,x,y){var p=0;return r([x,t],{declaredClass:"jimu.dijit.Popup",baseClass:"jimu-popup",titleLabel:"",content:null,container:null,customZIndex:null,buttons:[],enabledButtons:[],disabledButtons:[],onClose:null,_fixedHeight:!1,autoHeight:!1,isResize:!0,horizontalWidthRate:0,maxHeight:800,
maxWidth:1024,enableMoveable:!0,hasTitle:!0,contentHasNoMargin:!1,hasOverlay:!0,moveToCenter:!0,customPosition:null,hiddenAfterInit:!1,constructor:function(){this.buttons=[];this.enabledButtons=[];this.disabledButtons=[];this.pauseKeyHandles=[];this.container=jimuConfig.layoutId},postCreate:function(){this._preProcessing();this.inherited(arguments);this._initDomNode();this._addStylesByHeightType();this._calcAndSetPosition();b.place(this.domNode,this.container);setTimeout(e.hitch(this,function(){this._calcAndSetPosition(!0,
!1)}),50);this.isResize&&this.own(h(window,"resize",e.hitch(this,function(){this._calcAndSetPosition(!0,!0)})));this.hasOverlay&&(this.overlayNode=b.create("div",{"class":"jimu-overlay"},this.container));this.customZIndex||0===this.customZIndex?(b.setStyle(this.domNode,"zIndex",this.customZIndex+1),this.overlayNode&&b.setStyle(this.overlayNode,"zIndex",this.customZIndex)):this._increaseZIndex();this.hiddenAfterInit&&this.hide();q.animateProperty({node:this.domNode,properties:{opacity:1},duration:200}).play();
this.domNode.focus()},_preProcessing:function(){"number"!==typeof this.width&&(this.width=this.maxWidth);"number"===typeof this.height&&(this._fixedHeight=!0,this.autoHeight=!1);this.autoHeight&&(this.maxHeight=598)},_createTitleNode:function(){this.titleNode=b.create("div",{"class":"title"},this.domNode);this.titleLabeNode=b.create("span",{"class":"title-label jimu-float-leading",innerHTML:this.titleLabel||"\x26nbsp"},this.titleNode);this.closeBtnNode=b.create("div",{"class":"close-btn jimu-icon jimu-icon-close jimu-float-trailing"},
this.titleNode);var a=null,a="ontouchstart"in document?v.press:"click";this.own(h(this.closeBtnNode,a,e.hitch(this,this.close)))},_initDomNode:function(){this.hasTitle&&this._createTitleNode();this.contentContainerNode=b.create("div",{"class":"content"},this.domNode);this.content&&("string"===typeof this.content?this.contentContainerNode.innerHTML=this.content:this.content.domNode?(this.content.placeAt(this.contentContainerNode),this.content.popup=this):1===this.content.nodeType&&b.place(this.content,
this.contentContainerNode));this.buttonContainer=b.create("div",{"class":"button-container"},this.domNode);0===this.buttons.length&&b.setStyle(this.buttonContainer,"display","none");for(var a=this.buttons.length-1;-1<a;a--)this._createButton(this.buttons[a]),this.buttons[a].disable&&this.disableButton(a)},_limitButtonsMaxWidth:function(){var a=this.enabledButtons.length;if(0!==a){var d=b.getContentBox(this.buttonContainer),c=b.getMarginExtents(this.enabledButtons[0]),m=b.getPadBorderExtents(this.enabledButtons[0]),
k=0,m=8===u("ie")?m.l+m.r:0,k=(d.w-(c.l+c.r+m)*a)/a;0<k&&(f.forEach(this.enabledButtons,e.hitch(this,function(a){b.setStyle(a,"maxWidth",k+"px")})),f.forEach(this.disabledButtons,e.hitch(this,function(a){b.setStyle(a,"maxWidth",k+"px")})))}},_moveableNode:function(a,d){this.moveable&&(this.moveable.destroy(),this.moveable=null);var c=b.getMarginBox(this.container);c.l=c.l-a+d;c.w+=2*(a-d);this.moveable=new w.boxConstrainedMoveable(this.domNode,{box:c,handle:this.titleNode||this.contentContainerNode,
within:!0});this.own(h(this.moveable,"Moving",e.hitch(this,this.onMoving)));this.own(h(this.moveable,"MoveStop",e.hitch(this,this.onMoveStop)))},_getHeaderBox:function(){return 0===n("#header").length?{t:0,l:0,w:0,h:0}:b.getMarginBox("header")},_getFooterBox:function(){return 0===n(".footer",this.container).length?{t:0,l:0,w:0,h:0}:b.getMarginBox(n(".footer",this.container)[0])},_calcAndSetPosition:function(a,d){var c=b.getMarginBox(this.domNode);if("string"!==typeof this.container||b.byId(this.container)){var e=
b.getContentBox(this.container),k=this._getHeaderBox(),g=this._getFooterBox(),g=e.h-k.h-g.h-40,f=0,h=0;this.customPosition&&this.customPosition.height?(this.height=this.customPosition.height,h="number"===typeof this.height?this.height+"px":this.height):(this.height=this._fixedHeight?this.height>g?g:this.height:this.autoHeight?(c.h>g?g:c.h)||g-200:g>this.maxHeight?this.maxHeight:g,h=this.height+"px");this.customPosition&&this.customPosition.width?(this.width=this.customPosition.width,f="number"===
typeof this.width?this.width+"px":this.width):("number"===typeof this.horizontalWidthRate&&0<this.horizontalWidthRate?(f=b.getMarginBox(window.document.body).w*this.horizontalWidthRate,this.width=f=f>this.maxWidth?f:this.maxWidth):this.width=this.width||this.maxWidth,f=this.width+"px");var l=c=0;this.customPosition?(c="number"===typeof this.customPosition.left?this.customPosition.left+"px":this.customPosition.left,l="number"===typeof this.customPosition.top?this.customPosition.top+"px":this.customPosition.top):
this.moveToCenter&&(l=(g-this.height)/2+k.h+20,l=l<k.h?k.h:l,c=(e.w-this.width)/2+"px",l+="px");b.setStyle(this.domNode,{width:f,height:this.autoHeight?"auto":h,left:c,top:l});this.enableMoveable&&this._moveableNode(this.width,100);!this.moveToCenter&&a&&"block"===b.getStyle(this.domNode,"display")&&this.emit("popupHasInitedSuccessfully",d)}},setDomNodeStyls:function(a){b.setStyle(this.domNode,a)},setCustomPosition:function(a,d,c,e){this.width=c||this.width||this.maxWidth;this.height=e||this.height||
this.maxHeight;c="number"===typeof this.width?this.width+"px":this.width;e="number"===typeof this.height?this.height+"px":this.height;b.setStyle(this.domNode,{left:"number"===typeof a?a+"px":a,top:"number"===typeof d?d+"px":d,width:c,height:this.autoHeight?"auto":e})},_addStylesByHeightType:function(){this.autoHeight?(b.addClass(this.contentContainerNode,"content-static"),0===this.buttons.length&&b.setStyle(this.contentContainerNode,{marginBottom:"15px"})):(b.addClass(this.contentContainerNode,"content-absolute"),
this.hasTitle||b.addClass(this.contentContainerNode,"no-popup-title-content-absolute"),b.addClass(this.buttonContainer,"button-container-absolute"),0===this.buttons.length&&b.setStyle(this.contentContainerNode,{bottom:"15px"}));this.contentHasNoMargin&&b.addClass(this.contentContainerNode,"content-fill-Popup")},_increaseZIndex:function(){b.setStyle(this.domNode,"zIndex",p+200+1);this.overlayNode&&b.setStyle(this.overlayNode,"zIndex",p+200);p++},setTitleLabel:function(a){this.titleNode.innerHTML=y.stripHTML(a)},
onMoving:function(a){b.setStyle(a.node,"opacity",.9)},onMoveStop:function(a){b.setStyle(a.node,"opacity",1)},show:function(){this.overlayNode&&b.setStyle(this.overlayNode,"display","block");b.setStyle(this.domNode,"display","block")},hide:function(){this.overlayNode&&b.setStyle(this.overlayNode,"display","none");b.setStyle(this.domNode,"display","none")},close:function(){if(!this.onClose||!1!==this.onClose()){var a=this.domNode.parentNode,d=e.clone(this.domNode);b.setStyle(this.domNode,"display",
"none");this.overlayNode&&b.destroy(this.overlayNode);this.destroy();this.moveable&&this.moveable.destroy();b.place(d,a);q.animateProperty({node:d,properties:{opacity:0},duration:200,onEnd:function(){b.destroy(d)}}).play()}},addButton:function(a){this._createButton(a)},_createButton:function(a){var d=" ";a.classNames&&0<a.classNames.length&&"function"===typeof a.classNames.join&&(d+=a.classNames.join(" "));var c=b.create("div",{"class":"jimu-btn jimu-popup-action-btn jimu-float-trailing jimu-trailing-margin1 "+
d,innerHTML:a.label,title:a.title||a.label},this.buttonContainer);this.enabledButtons.unshift(c);d=b.create("div",{"class":"jimu-btn jimu-state-disabled jimu-float-trailing jimu-trailing-margin1 "+d,title:a.title||a.label,innerHTML:a.label,style:{display:"none"}},this.buttonContainer);this.disabledButtons.unshift(d);this.own(h(c,"click",e.hitch(this,function(b){if(a.onClick)a.onClick(b);else this.close()})))},setButtonProps:function(a,d){"number"===typeof a&&isFinite(a)||(d=a,a=0);if(d&&0!==this.enabledButtons.length)for(var c in d)"title"===
c?(b.setAttr(this.enabledButtons[a],"title",d[c]),b.setAttr(this.disabledButtons[a],"title",d[c])):"label"===c&&(b.setProp(this.enabledButtons[a],"innerHTML",d[c]),b.setProp(this.disabledButtons[a],"innerHTML",d[c]))},enableButton:function(a){"number"===typeof a&&isFinite(a)&&a<this.enabledButtons.length?(b.setStyle(this.enabledButtons[a],"display","inline-block"),b.setStyle(this.disabledButtons[a],"display","none")):(f.forEach(this.enabledButtons[a],e.hitch(this,function(a){b.setStyle(a,"display",
"inline-block")})),f.forEach(this.disabledButtons[a],e.hitch(this,function(a){b.setStyle(a,"display","none")})))},disableButton:function(a){"number"===typeof a&&isFinite(a)&&a<this.disabledButtons.length?(b.setStyle(this.disabledButtons[a],"display","inline-block"),b.setStyle(this.enabledButtons[a],"display","none")):(f.forEach(this.disabledButtons,e.hitch(this,function(a){b.setStyle(a,"display","inline-block")})),f.forEach(this.enabledButtons,e.hitch(this,function(a){b.setStyle(a,"display","none")})))},
showButton:function(a){this.enableButton(a)},hideButton:function(a){"number"===typeof a&&isFinite(a)&&a<this.disabledButtons.length?(b.setStyle(this.disabledButtons[a],"display","none"),b.setStyle(this.enabledButtons[a],"display","none")):(f.forEach(this.disabledButtons,e.hitch(this,function(a){b.setStyle(a,"display","none")})),f.forEach(this.enabledButtons,e.hitch(this,function(a){b.setStyle(a,"display","none")})))},resize:function(a){a&&(this.width=a.w,this.height=a.h);this._calcAndSetPosition();
this.content&&this.content.domNode&&this.content.resize&&this.content.resize()}})});