// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/Deferred dojo/DeferredList dojo/Evented dojox/data/CsvStore dojo/store/Observable dojo/store/Memory esri/graphicsUtils esri/geometry/webMercatorUtils esri/geometry/Point esri/layers/FeatureLayer esri/tasks/locator esri/tasks/query esri/SpatialReference esri/dijit/PopupTemplate esri/geometry/geometryEngine esri/tasks/ProjectParameters esri/tasks/GeometryService esri/request jimu/utils moment/moment".split(" "),function(E,k,g,t,z,F,G,
H,I,J,K,A,L,M,B,C,N,D,O,P,Q,v,R){return E([F],{file:null,map:null,spatialReference:null,fsFields:[],duplicateTestFields:[],geocodeSources:[],duplicateData:[],data:null,editLayer:null,parent:null,separatorCharacter:null,csvStore:null,storeItems:null,matchedFeatureLayer:null,mappedArrayFields:null,unMatchedFeatureLayer:null,duplicateFeatureLayer:null,addrFieldName:"",xFieldName:"",yFieldName:"",symbol:null,matchFieldPrefix:"MatchField_",_internalFields:[],_removeLocators:[],constructor:function(a){g.mixin(this,
a);this.useAddr=!0;this.objectIdField="ObjectID";this.nls=a.nls;this.minScore=90;this._getDuplicateFields(this.fsFields);this.spatialReference=this.map.spatialReference;this.decimalSeperator=/^1(.+)1$/.exec(v.localizeNumber(1.1))[1].toString()},_getDuplicateFields:function(a){var b=[];k.forEach(a,function(a){a.duplicate&&b.push(a.name)});this.duplicateTestFields=b},handleCsv:function(){var a=new t;if(this.file&&!this.file.data){var b=new FileReader;b.onload=g.hitch(this,function(){this.data=b.result;
this._processCsvData().then(function(b){a.resolve(b)})});b.readAsText(this.file)}return a},_processCsvData:function(){var a=new t;this._convertSources();this._getSeparator();this._getCsvStore().then(function(b){a.resolve(b)});return a},processForm:function(){this._internalFields=["DestinationOID","matchScore","hasDuplicateUpdates","duplicateState"];this._matchFields=[];var a=new t;this._locateData(this.useAddr).then(g.hitch(this,function(b){var f=[],h=[],c=[],m={},d=0,e=0;0<this._removeLocators.length&&
(this._removeLocators.sort(function(a,d){return d-a}),k.forEach(this._removeLocators,g.hitch(this,function(a){this._geocodeSources.splice(a,1)})));for(var q=function(a,d,b,e){var m=a;-1===[null,void 0,""].indexOf(a)&&a.indexOf&&-1<a.indexOf(d)&&(b=b.filter(function(a){return a.keyField===e}))&&b.hasOwnProperty("length")&&1===b.length&&(m=a.toString?a.toString().replace(d,"."):a);return m},w=Object.keys(b),n=0;n<w.length;n++){var l={},p=b[w[n]],u=this.storeItems[p.csvIndex];k.forEach(this.fsFields,
g.hitch(this,function(a){if(this.mappedArrayFields.hasOwnProperty(a.name))if(this.mappedArrayFields[a.name]){var d=this.csvStore.getValue(u,this.mappedArrayFields[a.name]);if(a.domainValues){var b=a.domainValues.filter(g.hitch(this,function(a){return a.label===d}));l[a.name]=b&&0<b.length?b[0].value:d}else l[a.name]="."===this.decimalSeperator||this.useAddr?d:q(d,this.decimalSeperator,this._currentAddressFields,this.mappedArrayFields[a.name])}else l[a.name]=void 0}));k.forEach(this._currentAddressFields,
g.hitch(this,function(a){var d=this.matchFieldPrefix+a.keyField;if("undefined"!==typeof a.value){var b=this.csvStore.getValue(u,a.value);l[d]="."===this.decimalSeperator||this.useAddr?b:q(b,this.decimalSeperator,this._currentAddressFields,a.keyField)}else l[d]=void 0;this._matchFields.push(d)}));p&&p.score>this.minScore?(l.ObjectID=n-d-e,l.matchScore=p.score,f.push({geometry:p.location,attributes:g.clone(l)})):p.isDuplicate?(l.ObjectID=e,l.DestinationOID=p.featureAttributes[this.editLayer.objectIdField],
l.matchScore=100,l.hasDuplicateUpdates=!1,l.duplicateState="no-change",c.push({geometry:p.location,attributes:g.clone(l)}),m[e]=p.featureAttributes,e++):(l.ObjectID=d,l.matchScore=p.score?p.score:0,h.push({geometry:p.location&&p.location.type?p.location:new A(0,0,this.spatialReference),attributes:g.clone(l)}),d++)}this.matchedFeatureLayer=this._initLayer(f,this.file.name.replace(".csv",""));0<c.length&&(this.duplicateFeatureLayer=this._initLayer(c,this.file.name.replace(".csv","")+"_Duplicate"));
0<h.length&&(this.unMatchedFeatureLayer=this._initLayer(h,this.file.name.replace(".csv","")+"_UnMatched"));a.resolve({matchedLayer:this.matchedFeatureLayer,unMatchedLayer:this.unMatchedFeatureLayer,duplicateLayer:this.duplicateFeatureLayer,duplicateLookupList:m})}),function(b){a.reject(b,!0)});return a},_initLayer:function(a,b){a=this._generateFC(a);b=new L(a,{id:b,editable:!0,outFields:["*"]});this._initPopup(b);this.map.addLayers([b]);return b},_initPopup:function(a){var b={title:a.id+": {"+this.labelField+
"}"},f=[];k.forEach(a.fields,g.hitch(this,function(a){a.name!==this.objectIdField&&-1===this._internalFields.indexOf(a.name)&&-1===this._matchFields.indexOf(a.name)&&f.push({fieldName:a.name,visible:!0})}));b.fieldInfos=f;a.infoTemplate=new N(b)},_findDuplicates:function(){var a=new t;this._getAllLayerFeatures(this.editLayer,this.fsFields).then(g.hitch(this,function(b){this.keys=Object.keys(this.mappedArrayFields);this.oidField=this.editLayer.objectIdField;var f=[],h=[],c=this.duplicateTestFields;
c&&c.hasOwnProperty("length")&&0<c.length&&k.forEach(this.storeItems,g.hitch(this,function(a){var d={compareValues:{},fileId:a._csvId,featureId:-1};k.forEach(c,g.hitch(this,function(b){var e=this.mappedArrayFields[b];"undefined"!==typeof e&&(d.compareValues[b]=this.csvStore.getValue(a,e),-1===h.indexOf(b)&&h.push(b))}));0<Object.keys(d.compareValues).length&&f.push(d)}));var m=[];0<f.length&&k.forEach(f,g.hitch(this,function(a){k.forEach(b,g.hitch(this,function(b){var d={};k.forEach(h,g.hitch(this,
function(a){var e=b.attributes[a];d[a]=-1===[null,void 0].indexOf(e)&&e.toString?e.toString():e}));if(JSON.stringify(a.compareValues)===JSON.stringify(d)){var e=b.attributes[this.oidField];-1!==a.featureId?(a.hasMultiDuplicates=!0,"undefined"===typeof a.featureIds?(a.featureIds=[a.featureId,e],a.features=[a.feature,b]):(a.featureIds.push(e),a.features.push(b))):(a.featureId=e,a.feature=b,m.push(a))}}))}));a.resolve(m)}));return a},_getAllLayerFeatures:function(a,b){var f=new t,h=[this.editLayer.objectIdField];
k.forEach(b,function(a){a.name&&h.push(a.name)});2>h.length&&(h=b);var c=a.maxRecordCount;b=new B;b.where="1\x3d1";a.queryIds(b).then(function(b){var d=[],e,m;if(b&&0<b.length){e=0;for(m=b.length;e<m;e+=c){var k=new B;k.outFields=h;k.objectIds=b.slice(e,e+c);k.returnGeometry=!0;d.push(a.queryFeatures(k))}(new z(d)).then(g.hitch(this,function(a){if(a){for(var b=[],d=0;d<a.length;d++)a[d][1].features&&b.push.apply(b,a[d][1].features.map(function(a){return{geometry:a.geometry,attributes:a.attributes}}));
f.resolve(b)}}))}else f.resolve([])},function(a){console.error(a);f.resolve({type:"error",message:a})});return f},_locateData:function(a){var b=new t;this._findDuplicates().then(g.hitch(this,function(f){this.duplicateData=f;if(a){var h=g.hitch(this,function(a,b,d){var e=new t,f=this._geocodeSources[b],c=f.locator;c.outSpatialReference=this.spatialReference;var m=[],l=[],p=0,u,r;u=0;r=a.length;for(;u<r;u+=500){var x=a.slice(u,u+500),y=[];(f.singleEnabled||f.multiEnabled)&&k.forEach(x,g.hitch(this,
function(a){var b=a._csvId,e=null,c;a:for(c in this.duplicateData){var h=this.duplicateData[c];if(h.fileId===b){e=g.mixin({},h);delete this.duplicateData[c];break a}}var m={};m.OBJECTID=b;this.useMultiFields?k.forEach(this.multiFields,g.hitch(this,function(b){this._currentAddressFields=this.multiFields;if(b.value!==this.nls.noValue){var d=this.csvStore.getValue(a,b.value);m[b.keyField]=d}else m[b.keyField]=void 0})):this.singleFields[0].value!==this.nls.noValue&&(this._currentAddressFields=this.singleFields,
c=this.csvStore.getValue(a,this.singleFields[0].value),"undefined"===typeof c&&(c=typeof c+b),m[f.singleLineFieldName]=c);c=g.mixin({},m);delete c.OBJECTID;c=JSON.stringify(c);if(null===e)y.push(m),d[c]={index:p,csvIndex:b,location:{}},p+=1;else if(null!==e){var h=e.feature.geometry,l=e.feature.attributes;if(-1!==[null,void 0].indexOf(h)&&e.features){var n=0;a:for(;n<e.features.length;n++){var q=e.features[n];if(-1===[null,void 0].indexOf(q.geometry)){h=q.geometry;l=q.attributes;break a}}}d[c]={index:-1,
csvIndex:b,isDuplicate:!0,location:g.mixin({},h),featureAttributes:l}}}));this.useMultiFields&&f.multiEnabled||!this.useMultiFields&&f.singleEnabled?l.push(c.addressesToLocations({addresses:y,countryCode:f.countryCode,outFields:["ResultID","Score"]})):(x=new t,x.reject(this.nls.warningsAndErrors.notConfigured,!0),l.push(x))}var v=Object.keys(d);(new z(l)).then(g.hitch(this,function(c){this.minScore=this._geocodeSources[b]?this._geocodeSources[b].minCandidateScore:90;b+=1;var l=this._geocodeSources.length>
b;if(c&&c.length&&c[0].length&&!1===c[0][0])if(1<c[0].length&&console.error(c[0][1]),(this.useMultiFields&&f.multiEnabled||!this.useMultiFields&&f.singleEnabled)&&this.parent.locatorError(this._geocodeSources[b-1].locator.url,!1),this._removeLocators.push(b-1),l)h(this._remainingStoreItems||this.storeItems,b,this._currentFinalResults||{}).then(g.hitch(this,function(a){e.resolve(a)}));else return 1<this._geocodeSources.length?e.resolve(d):e.reject(this.nls.warningsAndErrors.noMoreLocators),e.promise;
else if(c){var n=this.minScore,p=0;k.forEach(c,g.hitch(this,function(b){b=b[1];k.forEach(b,function(a){a.ResultID=a.attributes.ResultID});b=H(new I({data:b,idProperty:"ResultID"})).query({},{sort:[{attribute:"ResultID"}]});k.forEach(b,g.hitch(this,function(b){for(var e in v){var c=v[e];if(d[c]&&d[c].index===p){b.attributes.Score<n?l?(m.push(a[d[c].csvIndex]),delete d[c]):d[c].score=b.attributes.Score:(d[c].location=b.location,d[c].score=b.attributes.Score,delete d[c].index);delete v[e];break}}p+=
1}))}));if(l&&0<m.length)this._remainingStoreItems=m,this._currentFinalResults=d,h(m,b,d).then(g.hitch(this,function(a){e.resolve(a)}));else return e.resolve(d),e.promise}}),g.hitch(this,function(a){console.log(a);b+=1;if(this._geocodeSources.length>b)h(this._remainingStoreItems||this.storeItems,b,this._currentFinalResults||{}).then(g.hitch(this,function(a){e.resolve(a)}));else return 1<this._geocodeSources.length?e.resolve(d):e.reject(this.nls.warningsAndErrors.noMoreLocators),e.promise}));return e});
this._removeLocators=[];h(this.storeItems,0,{}).then(g.hitch(this,function(a){b.resolve(a)}))}else this._currentAddressFields=[{keyField:this.xFieldName,label:this.xFieldName,value:this.xFieldName},{keyField:this.yFieldName,label:this.yFieldName,value:this.yFieldName}],this._xyData({storeItems:this.storeItems,csvStore:this.csvStore,xFieldName:this.xFieldName,yFieldName:this.yFieldName,wkid:this.spatialReference.wkid}).then(g.hitch(this,function(a){if(this.isGeographic&&!this.map.spatialReference.isWebMercator()&&
4326!==this.spatialReference.wkid){var c=[];k.forEach(a,function(a){c.push(a.location)});var d=1<c.length?D.union(c):D.buffer(c[0],100,9001);this._projectPoints(d,c).then(function(d){for(var c=0;c<a.length;c++)a[c].location=d[c];b.resolve(a)})}else b.resolve(a)}),function(a){b.reject(a)})}));return b},_xyData:function(a){var b=new t,f=[],h=a.csvStore;k.forEach(a.storeItems,g.hitch(this,function(b){var c=b._csvId,d=null,e;a:for(e in this.duplicateData){var q=this.duplicateData[e];if(q.fileId===c){d=
g.mixin({},q);delete this.duplicateData[e];break a}}var w={};e=h.getAttributes(b);k.forEach(e,function(a){w[a]=h.getValue(b,a)});e=!1;var n,l;null!==d&&d.feature&&d.feature.geometry?(q=d.feature.geometry,e=!0,l=d.feature.attributes):(n=h.getValue(b,a.xFieldName),d=h.getValue(b,a.yFieldName),"."!==this.decimalSeperator&&(n=-1!==[null,void 0,""].indexOf(n)?void 0:n.toString().replace(this.decimalSeperator,"."),d=-1!==[null,void 0,""].indexOf(d)?void 0:d.toString().replace(this.decimalSeperator,".")),
n=parseFloat(n),d=parseFloat(d),q=this._getGeometry(n,d),n=100);q&&f.push({attributes:w,location:q,csvIndex:c,score:n,isDuplicate:e,featureAttributes:l})}));b.resolve(f);return b},_getGeometry:function(a,b){"undefined"===typeof this.isGeographic&&(this.isGeographic=/(?=^[-]?\d{1,3}\.)^[-]?\d{1,3}\.\d+|(?=^[-]?\d{4,})|^[-]?\d{1,3}/.exec(a)?!0:!1);var f;isNaN(a)||isNaN(b)||(f=new A(a,b),this.isGeographic&&this.spatialReference.isWebMercator()?f=K.geographicToWebMercator(f):f.spatialReference=this.isGeographic&&
4326!==this.spatialReference.wkid?new C(4326):new C({wkid:this.spatialReference.wkid}));return f},_projectPoints:function(a,b){var f=new t;this.gsvc=new P(this.appConfig.geometryService);a={url:this.gsvc.url+"/findTransformations",content:{f:"json",inSR:a.spatialReference.wkid,outSR:this.spatialReference.wkid,extentOfInterest:JSON.stringify(a.getExtent().toJson())},handleAs:"json",callbackParamName:"callback"};Q(a,{usePost:!1}).then(g.hitch(this,function(a){a=(a=a&&a.transformations?a.transformations:
void 0)&&0<a.length?a[0].wkid:void 0;var c=new O;c.outSR=this.spatialReference;c.geometries=b;c.transformForward=!0;c.transformation=a;this.gsvc.project(c,g.hitch(this,function(a){f.resolve(a)}),function(a){f.reject(a)})}),function(a){f.reject(a)});return f},_generateFC:function(a){var b={layerDefinition:{geometryType:"esriGeometryPoint",spatialReference:this.spatialReference,objectIdField:this.objectIdField,type:"Feature Layer",drawingInfo:{renderer:{type:"simple",symbol:this.symbol}},fields:[{name:this.objectIdField,
alias:this.objectIdField,type:"esriFieldTypeOID"}]},featureSet:{features:a,geometryType:"esriGeometryPoint"}};k.forEach(this.fsFields,g.hitch(this,function(a){b.layerDefinition.fields.push({name:a.name,alias:a.label,type:a.value,editable:!0,domain:null})}));return b},clear:function(){this._removeLayer(this.matchedFeatureLayer);this._removeLayer(this.unMatchedFeatureLayer);this._removeLayer(this.duplicateFeatureLayer);this.storeItems=this.csvStore=this.separatorCharacter=this.data=this.fsFields=this.file=
void 0;this.duplicateData=[];this.mappedArrayFields=this.duplicateFeatureLayer=this.unMatchedFeatureLayer=this.matchedFeatureLayer=void 0;this.useAddr=!0;this.yFieldName=this.xFieldName=this.addrFieldName=""},_removeLayer:function(a){a&&(this.map.removeLayer(a),a.clear())},_getSeparator:function(){var a=this.data.indexOf("\n"),b=g.trim(this.data.substr(0,a)),f=0,h="";k.forEach([",","      ",";","|"],function(a){var c=b.split(a).length;c>f&&(f=c,h=a)});this.separatorCharacter=h},_getCsvStore:function(){var a=
new t;this.csvStore=new G({data:this.data,separator:this.separatorCharacter});this.csvStore.fetch({onComplete:g.hitch(this,function(b){this.storeItems=b;this._fetchFieldsAndUpdateForm(this.storeItems,this.csvStore,this.fsFields).then(function(b){a.resolve(b)})}),onError:function(b){console.error("Error fetching items from CSV store: ",b);a.reject(b)}});return a},_fetchFieldsAndUpdateForm:function(a,b,f){var g=new t,c=b._attributes,m=this.decimalSeperator,d={};k.forEach(c,function(c){k.forEach(a,function(a){var e=
!0,f=!0,g=!0,h=!0,k;d.hasOwnProperty(c)&&(f=d[c].supportsInt,g=d[c].supportsFloat,h=d[c].supportsDate,k=d[c].maxLength,f||g||h||(e=!1));var r=b.getValue(a,c);if(r){a=r.toString().length;var q=R(r);if(e){e=-1!==[null,void 0,""].indexOf(r);if(!e&&(h=h&&q.isValid()))if(q=r)try{h=!isNaN((new Date(q)).getTime())}catch(y){console.error(y),h=!1}else h=-1<[null,void 0,""].indexOf(q)?!0:!1;d[c]={supportsDate:h,supportsInt:e?f:!isNaN(parseInt(r,10))&&parseInt(r,10).toString().length===a&&f};"."!==m&&(r=e?"":
r.toString().replace(m,"."));d[c].supportsFloat=e?g:!isNaN(parseFloat(r))&&parseFloat(r).toString().length===a&&g}f=d[c];f.maxLength=k;"undefined"===typeof f.maxLength?f.maxLength=a:f.maxLength<a&&(f.maxLength=a)}})});g.resolve({fields:c,fieldTypes:d,fsFields:f});return g},_zoomToData:function(a,b){if(a&&0<a.length)try{var f=J.graphicsExtent(a);b?this.map.setExtent(f.expand(1.9),!0):this.map.setExtent(f,!0)}catch(h){console.log(h.message)}},_convertSources:function(){this.geocodeSources&&0<this.geocodeSources.length&&
(this._geocodeSources=k.map(this.geocodeSources,g.hitch(this,function(a){if(a&&a.url&&"locator"===a.type)return{locator:new M(a.url||""),outFields:["ResultID","Score"],singleLineFieldName:a.singleLineFieldName||"",name:v.stripHTML(a.name||""),placeholder:v.stripHTML(a.placeholder||""),countryCode:a.countryCode||"",addressFields:a.addressFields,singleEnabled:a.singleEnabled||!1,multiEnabled:a.multiEnabled||!1,minCandidateScore:a.minCandidateScore||90}})))}})});